### ISSUE TITLE
Search in multiple fields

### ISSUE THREAD

**Issue by Rtransat** [jarektkaczyk/eloquence#10]
Hi,

Can we search by multiple fields?

For example I want search by first and last name. If I search ```John Doe``` I want get the result for columns ```firstname``` and ```lastname``` with concatenation.

```firstname lastname``` or ```lastname firstname```

And can we use a filter panel to search with multiple input ?

For example in my case:

First name, Last name, etc

```php
$query = [];
$input = [];

if($request->get('company_name')) {
	$query[] = 'company_name';
	$input[] = 'company_name';
}

if($request->get('firstname')) {
	$query[] = 'contacts.firstname';
	$input[] = 'firstname';
}

if($request->get('lastname')) {
	$query[] = 'contacts.lastname';
	$input[] = 'lastname';
}

$clients = Client::search($request->only($input), $query)->with('contacts')->get();
```

Can I use AND operator to search only by fields filled by the user ?

Thx

**Comment by jarektkaczyk** [comment]
Will be easier if you show me real example. Basically you can prepare the search query by yourself, the way you need it. For example:

```
$query = [];
$query[] = $input->get('firstname') . ' ' . $input->get('lastname');
$query[] = $input->get('lastname') . ' ' . $input->get('firstname');

// if you're passing array instead of string as $query, then it's going to search phrases:
`name` like '%jarek tkaczyk%' or `name` like '%tkaczyk jarek%' ...
```

**Comment by Rtransat** [comment]
It doesn't work :/

```Column not found: 1054 Champ 'clients.firstname lastname' inconnu dans field list```

```
$query = [];
$input = [];

/*if($request->get('company_name')) {
	$query[] = 'company_name';
	$input[] = 'company_name';
}*/

$query[] = 'firstname' . ' ' . 'lastname';
$query[] = 'lastname' . ' ' . 'firstname';


$clients = Client::search($request->all(), $query)->with('contacts')->get();
```

And with $request->get() same except it form field name

**Comment by Rtransat** [comment]
My form as an example:
![search-filter](https://cloud.githubusercontent.com/assets/1011503/8495077/f4b3e40a-216a-11e5-8962-767941732da3.jpg)

The name of my input fields are: company_name, firstname, lastname

And the eloquent relation:

Client hasMany Contact

clients: company_name
contacts: firstname, lastname

If several fields are filled I want to query with AND operator

For example:
- Find me the firstname and lastname
- Find me the company name and the firstname

**Comment by jarektkaczyk** [comment]
@Rtransat No, that's not what you'd use this feature for. Its purpose is to easily search items with relevance score (most likely full text), while your example is rather about explicit search. That is, you would explicitly apply the conditions to your query depending on the filled fields.
