### ISSUE TITLE
Conflict with Sluggable (method replicate)

### ISSUE THREAD

**Issue by SergioGregorutti** [jarektkaczyk/eloquence#100]
Hi,

I'm using both packages (Eloquence and Sluggable) in my project with Laravel 5.2 and it seems like there's a blocker issue.

I get this error on my models:

`Trait method replicate has not been applied, because there are collisions with other trait methods on App\User`

This is because both packages have a "replicate" method and there's a conflict.

Can someone take a look at this?

Thanks in advance!

**Comment by jarektkaczyk** [comment]
use alias on trait's method:

```php
use Eloquence, [ other traits ] { 
    Eloquence::replicate as eloquenceReplicate; 
}
```

this way you lose eloquence features on `replicate` method, but you can use both traits.

**Comment by ghprod** [comment]
```
use Eloquence[, other traits ] { 
    Sluggable::replicate insteadof Eloquence;
}
```

I use like that..
