### ISSUE TITLE
Invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause

### ISSUE THREAD

**Issue by tr33m4n** [jarektkaczyk/eloquence#101]
Hi there,

Receiving this error when performing a search:

`SQLSTATE[HY000]: General error: 20018 Column 'ASC_CUS_TBL_OLD.CUS_CREATED' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. [20018] (severity 16) [(null)] (SQL: select top 30 * from (select [ASC_CUS_TBL_OLD].*, max(case when [ASC_CUS_TBL_OLD].[CUS_INV_NAME] = Oakwood then 15 else 0 end + case when [ASC_CUS_TBL_OLD].[CUS_INV_NAME] like Oakwood% then 5 else 0 end + case when [ASC_CUS_TBL_OLD].[CUS_INV_NAME] like %Oakwood% then 1 else 0 end) as relevance from [ASC_CUS_TBL_OLD] where ([ASC_CUS_TBL_OLD].[CUS_INV_NAME] like %Oakwood%) group by [ASC_CUS_TBL_OLD].[CUS_UNIQUE]) as [ASC_CUS_TBL_OLD] where [relevance] >= 0.25 order by [relevance] desc)`

The backend is an MSSQL database using the sqlsrv driver. CUS_CREATED is a timestamp in the format of 2016-07-06 11:24:46:000. Any ideas?

Thanks

**Comment by jarektkaczyk** [comment]
Not 100% sure about mssql, but I guess you need a subquery for this. That being said... I don't think you can use searchable, unless you find a way of changing your db behaviour in this matter.
