### ISSUE TITLE
Not getting results ordered by Relevance

### ISSUE THREAD

**Issue by wolfius** [jarektkaczyk/eloquence#102]
Hi!

I'm searching for Dealership names where all names begin with the brand name (eg. Mazda -X-).

If I search with -X- I get the results I want, filtered just by that Dealership.

![screen shot 2016-07-08 at 11 40 14 am](https://cloud.githubusercontent.com/assets/1514442/16694862/18cf138a-4502-11e6-8d57-4068d328aa5f.png)

But if I search by "Mazda -X-", of course I get all the results because it matches all the Dealerships with "Mazda" in their name, but I would think that "Mazda -X-" has to be the top result, but as you can see in the screenshot, it's nowhere to be seen in the first page.

![screen shot 2016-07-08 at 11 40 35 am](https://cloud.githubusercontent.com/assets/1514442/16694910/87f393ee-4502-11e6-8fe3-433cfb87b7fa.png)

This happens also in other kind of searches on other fields like user names and last names, or in joined tables (eg. searching for dealership names from the salesmen table).

I've tried playing with the field weights with no positive results.

Any help would be appreciated! :)

**Comment by jarektkaczyk** [comment]
Have you managed to resolve tihs?
