### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by fridzema** [jarektkaczyk/eloquence#103]
Dear jarektkaczyk,

First i want to say, i really like your package!
But for my application i need a global search feature (search trough (all) models).
My temp fix for now is:
`
	  	$users = User::search($id, [
	  		'email', 
	  		'country.name', 
	  		'country.demonym', 
	  		'country.native_name'
	  		])->get();
			
			$companies = Company::search($id, [
					'company_code', 
					'statutory_name', 
					'company_name', 
					'display_name', 
					'telephone_number', 
					'email_address', 
					'website', 
					'btwnr', 
					'kvknr', 
					'taalcode'
				])->get();			

			$addresses = Address::search($id, [
					'street', 
					'number',
					'zip_code',
					'city',
					'direct_phone',
					'mobile_phone',
					'description',
		  		'country.name', 
		  		'country.demonym', 
		  		'country.native_name'
				])->get();
			
			$projects = Project::search($id, [
				'project_code', 
				'naming_convention_free',
	  		'Countries.name', 
	  		'Countries.demonym', 
	  		'Countries.native_name'
				])->get();

    $app = app();
    $results = $app->make('stdClass');
    $results->users = $users;
    $results->companies = $companies;
    $results->addresses = $addresses;
    $results->projects = $projects;`  

But this by far not the best way to go is guess...
I want the results of all items displayed at relevance of the searchterm.

I hope you can help me out with this braincracker!

**Comment by jarektkaczyk** [comment]
Have you managed to resolve this already?

In such case I would probably go with DB level relevance scoring using eg. levenshtein or better something more robust, like algolia, solr etc.

Joining all these tables might not be the best for perf.

**Comment by fridzema** [comment]
Thanks for your reaction!
I tried elasticsearch before and a few others, but i find it a bit complex for what i am trying to achieve at the moment.
For now i am testing the new [https://laravel.com/docs/5.3/scout]
