### ISSUE TITLE
Searching with "and" instead of "or"

### ISSUE THREAD

**Issue by ksdev-pl** [jarektkaczyk/eloquence#104]
Hi

Related to https://github.com/nicolaslopezj/searchable/issues/114

Is it possible to search for "one" AND "two" instead of "one" OR "two" when searching for "one two"?

**Comment by jarektkaczyk** [comment]
Yes, take this as example `' " one * two " '` but mind that order matters, so if you want to find two one as well, provide it as 2nd phrase to search

**Comment by chiu0602** [comment]
@jarektkaczyk Sorry I don't understand, would you please provide more detail? Thanks!
