### ISSUE TITLE
new branch - adjust for BC breaking changes in L5.1

### ISSUE THREAD

**Issue by jarektkaczyk** [jarektkaczyk/eloquence#11]
Laravel 5.1 introduced BC breaking changes in `illuminate\database` among others, so a new branch for L5.1+ will be created.

**Comment by ziming** [comment]
Ah, is it in any way related to the earlier issue I reported?

**Comment by jarektkaczyk** [comment]
I don't think so.

**Comment by kfirba** [comment]
@jarektkaczyk will it be done anytime soon? I plan to use this extension since it looks awesome :) I'm actually going to use it in a Lumen 5.1 application but I don't think it would matter :x

**Comment by jarektkaczyk** [comment]
@kfirba Yep, a day or two.

**Comment by kfirba** [comment]
@jarektkaczyk awesome! I will be waiting then :)

Hopefully I will be able to study the package after I'm done with my project so I will be able to contribute :)

**Comment by kfirba** [comment]
@jarektkaczyk Just as a side note, I hope there will be some additions to the documentation. The base eloquence trait isn't documented as well as the joiner, they both say "soon" :confused: 

P.S. the `todo` list is amazing :) Hope we can see those features available soon

**Comment by jarektkaczyk** [comment]
@kfirba wiki updated a bit

**Comment by kfirba** [comment]
@jarektkaczyk Thanks! Am I right to assume that for Lumen 5.1 I will need to use the 5.1 branch?

**Comment by jarektkaczyk** [comment]
@kfirba it's for `illuminate/database` 5.1 to be precise, so yeah.
