### ISSUE TITLE
laravel 5.3 JoinClause error

### ISSUE THREAD

**Issue by terrylow** [jarektkaczyk/eloquence#112]
current installed sofa/eloquence 5.3 but after the upgrade to laravel 5.3, i received
Type error: Argument 1 passed to Illuminate\Database\Query\JoinClause::__construct() must be an instance of Illuminate\Database\Query\Builder, string given, called in /xxx/vendor/sofa/eloquence/src/Relations/Joiner.php

it seem the problem is due to JoinClause has been rewritten in laravel side

**Comment by jarektkaczyk** [comment]
Hey @terrylow , yes, new `JoinClause` breaks joining relations, that's why I worked on it right now.

It's done, so just update the package and you'll be fine! https://travis-ci.org/jarektkaczyk/eloquence/builds/154930836
