### ISSUE TITLE
Add meta attribute to existing model.

### ISSUE THREAD

**Issue by lukasoppermann** [jarektkaczyk/eloquence#114]
Hey,

so when I `new` up a new user I can attach meta attributes, however when I retrieve a user I can not.

Is this by design? I think it would be pretty useful, as for example with a user you might want to add meta info later on without creating "empty" meta fields on user creation.

**Comment by jarektkaczyk** [comment]
Can you elaborate?

**Comment by lukasoppermann** [comment]
Ahh, sure, what I tried to do is the following:

```php
$user = User::find(1);
$user->nickname = 'Jake';
$user->save();
```

It does return the nickname if I return the model now, but it is not persisted in the database.

However the following works:

```php
$user = new User([/* … */]);
$user->nickname = 'Jake';
$user->save();
```

Now the nickname is persisted in the database. Is that what you meant? Otherwise, please let me know what you need more info about.

**Comment by jarektkaczyk** [comment]
Hmm this alone would work without eloquence, are you sure you have eloquence and metable traits in the model? I won't be able to investigate it until Monday. 
Try this : `$user->`

**Comment by lukasoppermann** [comment]
Hey,

so with this code:

```php
        $user = \App\Models\User::find(5);
        $user->test = 'Test';
        $user->save();
        return $user->getMetaAttributes();
```

I get this return (nick is in the database from before). However the database has not been updated, `test` is not in the database.

```json
{
    "nick": {
        "meta_key": "nick",
        "meta_value": "Luke",
        "meta_type": "string"
    },
    "test": {
        "meta_key": "test",
        "meta_type": "string",
        "meta_value": "Test"
    }
}
```

My User model looks like this:

```php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Mpociot\Teamwork\Traits\UserHasTeams;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Metable;

class User extends Authenticatable
{
    use Notifiable, HasRoles, UserHasTeams, Eloquence, Metable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

```

Did I forget anything?

**Comment by jarektkaczyk** [comment]
Looks fine, should work. If doesn't, it seems there was some change in latest version that breaks it. I'll take a look on Monday, meanwhile as a last resort, check if the query on meta_attributes is executed at all:

```php
DB::enableQueryLog () 
.. Your code with save
dd(DB::getQueryLog()) 
```

**Comment by lukasoppermann** [comment]
Nope, it is not.

```php
array:3 [▼
  0 => array:3 [▼
    "query" => "select * from "users" where "users"."id" = ? limit 1"
    "bindings" => array:1 [▼
      0 => 5
    ]
    "time" => 0.11
  ]
  1 => array:3 [▼
    "query" => "pragma table_info(users)"
    "bindings" => []
    "time" => 0.11
  ]
  2 => array:3 [▼
    "query" => "select * from "meta_attributes" where "meta_attributes"."metable_id" in (?) and "meta_attributes"."metable_type" = ?"
    "bindings" => array:2 [▼
      0 => 5
      1 => "App\Models\User"
    ]
    "time" => 0.13
  ]
]
```

**Comment by jarektkaczyk** [comment]
Hmm just looked at it again and it seems fine - you load use and UT already has nick meta attr, right? 
So $user - >nick should show the value. 

If that's the case then maybe you just can't see it in the array/json version?

**Comment by lukasoppermann** [comment]
I am not quite sure what you mean.

`nick` was created when `creating` the model. So this is in the DB and does show up.

However, the `test` attribute is not added to the database.

**Comment by jarektkaczyk** [comment]
Ooo ok i know what the problem is. Save doesn't return true anymore of model want dirty, and then metable won't fire... Can't fix it till Monday

**Comment by lukasoppermann** [comment]
Just found this out as well.

**Comment by lukasoppermann** [comment]
Okay, so you have an idea of how to fix it than?

**Comment by lukasoppermann** [comment]
Is there a quick-fix I can apply until you can fix it on monday?

**Comment by jarektkaczyk** [comment]
composer update ;) 

I made a gothic to hookable that should do. Let me know if it's ok

**Comment by jarektkaczyk** [comment]
Hotfix*

**Comment by lukasoppermann** [comment]
Yes, this solved it. Thank you very much for the very quick fix.
