### ISSUE TITLE
SQLSTATE[HY093]: Invalid parameter number when adding join column in 5.3

### ISSUE THREAD

**Issue by andyappitized** [jarektkaczyk/eloquence#115]
When I added a relations column as a searchableColumn I am receiving an invalid parameter number, but when I remove the column it works.

Example: 

This produces the error:

`protected $searchableColumns = ['company_name','first_name','middle_name','last_name','email','address.address_line_1','address.postcode'];`

Removing the address relation fixes this:

`protected $searchableColumns = ['company_name','first_name','middle_name','last_name','email'];`

Following in the controller:

`Customer::search('*' . $request->get('search'). '*')->paginate(10)`

**Comment by jarektkaczyk** [comment]
Just tested, works fine for me.

Show your exact setup and code you're executing.

**Comment by andyappitized** [comment]
Issue seems to be with Builder.php line 130:

```
$joinBindings = collect($subquery->getQuery()->joins)->flatMap(function ($join) {
            $join->getBindings();
        })->all();
```

flatMap is not returning so $joinBindings is always null. This fixed my issue:

```
$joinBindings = collect($subquery->getQuery()->joins)->flatMap(function ($join) {
            return $join->getBindings();
        })->all();
```

**Comment by jarektkaczyk** [comment]
Yep, fixed, `composer update` and let me know, since I can't test w/o your data.

**Comment by andyappitized** [comment]
Working fine now 😄
