### ISSUE TITLE
Strange behavior using pagination and withCount

### ISSUE THREAD

**Issue by mauricius** [jarektkaczyk/eloquence#116]
I'm currently using Eloquence for model searching and I noticed a strange behavior using pagination and `withCount`. I have the following model:

``` php
class Customer extends Model 
{
    use Eloquence;

    protected $searchableColumns = [
        'lastname'  => 10,
        'firstname' => 5,
        'email'     => 7
    ];

    public function carts() {
        return $this->hasMany('Cart', 'customer_id', 'id');
    }

    public function orders() {
        return $this->hasMany('Order', 'customer_id', 'id');
    }
}
```

In my query I need to paginate the customers with the count relation on both orders and carts. So in my controller I'm using the following code

``` php
Customer::withCount(['orders', 'carts' => function($q) {
    $q->where('ordered', 0);
}])->search($value)->paginate();
```

If `$value` is populated the result is always empty, no matter what the search term is. It works only when one of the following conditions is met:
- the searched term is empty
- replacing `paginate` with `get`
- removing the where condition on the `carts` relationship

Tried to debug a little and I noticed that the problem is somewhere in the Laravel Query Builder, specifically in the `getCountForPagination` function, which in my case returns always 0, but the query logged by the debugbar is correct.

I'm using **Laravel 5.2.45** and Eloquence on 5.2 branch.

**Comment by jarektkaczyk** [comment]
what if you try `search(..)->withCount(..)->paginate()` ?

**Comment by mauricius** [comment]
I tried you suggestion before, but the result is the same.

**Comment by andybeesee** [comment]
I am experiencing the same issue, put together a sample app to show the behavior. Your suggestion to do withCount after the search (in my case a relation join) seems to solve it.
