### ISSUE TITLE
Is it possible to include custom attributes in search results?

### ISSUE THREAD

**Issue by levelel** [jarektkaczyk/eloquence#12]
For example,

```php
class Customer extends Model {
    use Eloquence;
    public function getBriefAttribute()
    {
        return $this->name;
    }
}
```

Is it possible to include this custom brief attribute in search result? 
So I can do this in javascript:

```javascript
// after fetch search result in var response
var brief = response.brief
```

I was trying so hard to return custom attributes in search results. Hope you can give me some hints. Thanks.

**Comment by jarektkaczyk** [comment]
You can use `Mappable` of this package, if you want to map `name` to `brief`. But first read the very end of [eloquent docs](http://laravel.com/docs/5.0/eloquent) about `$appends` and accessors.
