### ISSUE TITLE
Validable only creates validator for creation, not for updating

### ISSUE THREAD

**Issue by jojonas** [jarektkaczyk/eloquence#120]
I obtain a model instance using `$foo = Foo::find(123)`, then change some attributes, call `$foo->save()` and check whether `$foo->isValid()` (`Foo` uses the Validable trait).

Because [the default validator is created using `getCreateRules`](https://github.com/jarektkaczyk/eloquence/blob/5.3/src/Validable.php#L166), I get errors about unique constraints.
If `getValidator` would call `getUpdateRules` instead, it would fetch the correct rules (even in case of creation, where it would automatically fall back to `getCreateRules` since no key is assigned).

Is there anything that I am missing or is this a bug?

**Comment by jojonas** [comment]
I just noticed that another reason for the error could be that [the rules are being reset to `getCreateRules`](https://github.com/jarektkaczyk/eloquence/blob/5.3/src/Validable/Observer.php#L64) after updating. Thus, the second `->isValid()` validates against the create-rules.

**Comment by jarektkaczyk** [comment]
Yes, it seems this case is not handled correctly. However it works just fine in normal usage, that is when calling save/update/create.

**Comment by jojonas** [comment]
How do you get the validation result (as boolean) in that case? According to the [change log](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0), since Laravel 5.3, `->save()` return false also if nothing has changed in the model:

> Eloquent save Method

> The Eloquent save method now returns false if the model has not been changed since the last time it was retrieved or saved.

**Comment by jarektkaczyk** [comment]
That's a valid question ;) 
It needs to be addressed

**Comment by jarektkaczyk** [comment]
For now you can use getValidationErrors method and check whether there are any (after save).
