### ISSUE TITLE
Refined search - combination of words and relevance

### ISSUE THREAD

**Issue by seltix5** [jarektkaczyk/eloquence#122]
Hi,
first of all, great job here, this is so useful :D
and my question is : if i search for **one two** the query will show me results with **one** or **two** and will not give more relevance for results with **one two** in the searchable column and it should because the result really is more relevance in this situation.
the query should search for like **%one two%** or **%two one%** (maybe not so important this inverse combination?) or **%one%** or **%two%** with more relevance for the combinations with more keywords in it.
how can i do this?

thank you

**Comment by jarektkaczyk** [comment]
with default setup there are 2 ways:

```
$query->search('one two "one two"')
$query->search(['one', 'two', 'one two'])
```

This will search for whole phrase and each word separately.

**Comment by seltix5** [comment]
hi,
thank you for your reply.
the problem with this method is that it will not give more relevance for results with results with **one two**. The relevance will be the same for results with just one keyword or more and that is not really correct.

**Comment by jarektkaczyk** [comment]
It will give you higher score as sum of 'one two'+'one'

Jarek Tkaczyk

softonsofa :: development with pleasure

**Comment by seltix5** [comment]
hi,
it depends on the sample pool...

take this example, a search for **foto noivo** when there is a result with the name **foto noivos** (plural in the last word).

the query is :
`$query->search(['*foto noivo*', '*foto*', '*noivo*'])`

top results of the query :
https://postimg.org/image/n6pkt801j/

thank you.
