### ISSUE TITLE
work with laravel-translatable 

### ISSUE THREAD

**Issue by rommelandrea** [jarektkaczyk/eloquence#123]
Hi, it's possible to use the package to search in translated column created with laravel-translatable?
I tried to put joins in $searchable variable but search method return always all items in table

**Comment by jarektkaczyk** [comment]
Which translatable exactly?

**Comment by rommelandrea** [comment]
i use dimsav/laravel-translatable

**Comment by mtx-z** [comment]
dimsav/laravel-translatable use a "translations" relation on model, and make it easy to use by using magic properties and custom methods. But in the end, it's à relation.

**Comment by rommelandrea** [comment]
Thank you, now it's work.
If some one have the same issue the solution is insert in model:
protected $searchableColumns = ['translations.column_name'];
