### ISSUE TITLE
Search into string with several words using AND instead of OR

### ISSUE THREAD

**Issue by ncarreno** [jarektkaczyk/eloquence#129]
First of all, congratulations for your package, it is really cool.

I have for example a request like 'laravel install' but I have called my product 'install laravel' so what I am trying to do is looking for products when the title is '_laravel install_' but also '_laravel_' AND '_install_' so that the user can look my product 'install laravel'. Is there any way to do that?

I have tried:

```
            $string="'*laravel install*' * laravel * install*";

            $categories=Product::search($string)
                    ->where('visible', '=', 1)
                    ->where('relation', '>', 0)
                    ->groupBy('family_id')
                    ->get();
```

But it is showing me products only with the title laravel or install so it is showing many products I am not looking for. 

Is there any way to get more value for 'laravel install' than the other single words? Thank you!

**Comment by marcreichel** [comment]
+1

**Comment by Sennik** [comment]
+1

**Comment by marcreichel** [comment]
In my opinion the searching should be done via OR and the ordering should be done via AND so results which match more parts of the search string are rated higher.

**Comment by marcreichel** [comment]
Especially if the search string match more words in the same column.

**Comment by ncarreno** [comment]
@marcreichel How can I order via AND the results? Would you mind showing and example code? Thanks a lot

**Comment by marcreichel** [comment]
@ncarreno You definitely have to edit the core files of eloquence. Especially the Parser where the CASE ordering is done. Here you have to check one column of your database for each search query and combine these with AND. Clear?

One example:

Your search string: Laravel install
Now you have to do the following: Iterate through each search query (so "Laravel" on the one hand and "install" on the other hand) and make a CASE which adds points for each search query for ONE column. These have to be combined with AND. Multiple columns have to be combined with OR. So what do we get now?
If your title column matches "Laravel" and "install" this results is higher rated than results which only matches one of your search queries.

The Problem I see here is unfortunately "large search queries". So when your user searches for "How for gods sake do I install laravel" you would get a really really large SQL-query which could slow down your searching drastically.

At the moment I'm writing via my smartphone so I do not have a code example at hand but I hope this comment was helpful anyways.
