### ISSUE TITLE
No results when searching

### ISSUE THREAD

**Issue by wipeouttom** [jarektkaczyk/eloquence#141]
I have a model named Ticket. I left out the relationships for now.
```
<?php

namespace App;
use Sofa\Eloquence\Eloquence;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model {
    
    use Eloquence;
    
    protected $table = 'tickets';
    protected $primaryKey = 'id';
    public $timestamps = false;
    protected $fillable = ['cuser', 'forUser', 'title', 'body', 'status', 'category', 'hardwareid', 'priority'];
    
    protected $searchableColumns = ['id', 'cuser', 'forUser', 'title', 'body', 'status', 'category', 'hardwareid', 'priority'];
}
```
And in my controller i'm using the search function.

```
public function search() {
        $tickets = Ticket::search('AngularJS')->get();
        return view('Search\search', ['tickets' => $tickets]);
    }
```
When I go the the /search route, I display the tickets, but there are no results from the search. I do have tickets in my database. If I use this line of code with %'s it will work.

` $tickets = Ticket::search('%AngularJS%')->get();`

When I looked through the documentation it doesn't seem like thats the proper way to use the search function. Anyone able to help me out?

**Comment by jarektkaczyk** [comment]
`Ticket::search(['Angular JS'])` or `Ticket::serach('*Angular JS*', false)` will do the job
