### ISSUE TITLE
cleanPivotAttributes in BelongsToMany relation causes many queries for Metable models

### ISSUE THREAD

**Issue by kadet1090** [jarektkaczyk/eloquence#142]
When referencing Metable model in BeolongsToMany relationship, laravel is causing Eloquence to execute `hasMeta()` on every eagerly loaded model one by one and therefore produces a lot of unnecessary queries. One possible solution is to ban `pivot_*` meta names, so asking for existence of such attribute won't cause querying meta attributes.

Line 303 -> 326 of BelongsToMany.php in laravel causes that problem.

**Comment by jarektkaczyk** [comment]
thanks, PR would be welcome.

However, you can workaround it by using `->with('metaAttributes')` on the query OR `$models->load('metaAttributes')` on the model/collection.
