### ISSUE TITLE
[Mappable] Automatic eager-loaded relations doesn't work with mappable.

### ISSUE THREAD

**Issue by yansern** [jarektkaczyk/eloquence#143]
Hi, the following code won't work as Laravel doesn't resolve `photo_id` back to the original `fotoid` column name.

```php

protected $with = [
    'photos' // automatic eager loading
];

protected $maps = [
    'photo_id' => 'fotoid'    
];

public function photos()
{
    return $this->hasOne('App\Photos', 'id', 'photo_id'); // this uses mapped column name which laravel doesn't understand
}
```

**Comment by codedge** [comment]
Currently having the same problem. Any idea how to use the mapped name for a relation?

**Comment by jarektkaczyk** [comment]
@codedge sorry for late reply - sure, create PR I will review.

However, I strongly advise *NOT* to use too much eloquent magic, as it will be a pain in the ass (unless you have tiny little project and/or you work on it alone).

Too much magic is `appends` and `with` - I definitely never EVER use neither.
