### ISSUE TITLE
`Builder::search()` ignores value provided for `$threshold` when caller omits `$columns` arg

### ISSUE THREAD

**Issue by felthy** [jarektkaczyk/eloquence#144]
`Builder::search()` allows a call like this, where the `$columns` arg is omitted and the value `false` is taken as the value for `$fulltext` instead:

```php
$query = $this->getModel()->search('jarek tkaczyk', false);
```
(from [tests/SearchableBuilderTest.php:311](https://github.com/jarektkaczyk/eloquence/blob/5.3/tests/SearchableBuilderTest.php#L311))

However, in this call:

```php
$query = $this->getModel()->search('jarek tkaczyk', false, 40);
```

the value of `40` is ignored, instead of being used as the value for `$threshold`. The default of `null` is used instead.

**Comment by jarektkaczyk** [comment]
Something else was wrong here. This doesn't affect 3rd param.
