### ISSUE TITLE
Trait Methods Conflict 

### ISSUE THREAD

**Issue by naumanahmed19** [jarektkaczyk/eloquence#145]
Hi,

Thanks for package I have just added it to my project and after adding trait I am getting conflict with an other package.

https://github.com/cviebrock/eloquent-sluggable

So its just a suggestion kindly use a prefix for all methods.

**Comment by jarektkaczyk** [comment]
I encourage you to read this http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict
