### ISSUE TITLE
Validable conflicts with uniquewith-validator

### ISSUE THREAD

**Issue by zhanghuanchong** [jarektkaczyk/eloquence#146]
https://github.com/felixkiss/uniquewith-validator

Model can't be updated as the validator failed. The function "rules_for_update" in helpers.php will alter the rule has substring "unique". But the validator above use "unique_with" as the rule name...

Any fix for this? Maybe it will work if use "unique:" as substring checker, just like:

```
if (strpos($rule, 'unique:') === false) {
    return;
}
```

**Comment by jarektkaczyk** [comment]
Hmm it doesn't account for newer `unique_x` rules.

PR welcome
