### ISSUE TITLE
Exact match relevance value

### ISSUE THREAD

**Issue by cleitonsouza** [jarektkaczyk/eloquence#147]
This is a simple suggestion, I think this is important.

It would be very interesting that the relevance value in the queries, was greater than all the others when exactly what was searched (without word breaking) is found.

For example:
If I'm looking for clients like "john doe", the customer who has exactly that name does not appear first in the list.

**Comment by ridlwan** [comment]
+1

**Comment by gabrielbuzziv** [comment]
+1

**Comment by diego3g** [comment]
+1

**Comment by joaohenriqueabreu** [comment]
+1

**Comment by jarektkaczyk** [comment]
can be achieved by

**Comment by jarektkaczyk** [comment]
PR welcome

**Comment by jsdecena** [comment]
@cleitonsouza have you found a way for this?
