### ISSUE TITLE
Password reset conflict Laravel 5.3

### ISSUE THREAD

**Issue by wielski** [jarektkaczyk/eloquence#149]
Hi. This package has conflict with some 5.3 query builder functions.

`
BadMethodCallException in Builder.php line 2450:
Call to undefined method Sofa\Eloquence\Query\Builder::notify()
`

How to fix this error?

**Comment by jarektkaczyk** [comment]
it's not about the package - you probably forgot to use `Notifiable` on your model and sh.tty laravel exception handling for magic methods in eloquent lead you to `Builder` call.
