### ISSUE TITLE
skip validation when using model factories

### ISSUE THREAD

**Issue by kfirba** [jarektkaczyk/eloquence#15]
Hey.

If we use the validable trait along with model factory that simply is going to break very quickly. An example to that is that in my system I'm creating a user without the user "knowledge" and I do not persist store an email for him. When the user will manually register he will need to provide the email. The issue is that in my model factory I'm randomly creating users that may or may not have email addresses. 

When I'm doing it in my code I'm simply calling the `skipValidation` method, however I'm not sure how I can do that with model factories. Basically it means that some users are not persisted to my DB when trying to seed it.

**Comment by kfirba** [comment]
Just wanted to say that I got a workaround:

```php
factory('My\Model')->make($overrides)->each(function($m) {
    $model->skipValidation->save();
});
```

**Comment by jarektkaczyk** [comment]
@kfirba Depending on your needs, you may want to do what you did above, or use the builtin method for disabling EVENT HANDLERS with simple `$this->withoutEvents()`  http://laravel.com/docs/5.1/testing#mocking
