### ISSUE TITLE
Getting mapped attributes for Stored Procedure

### ISSUE THREAD

**Issue by codedge** [jarektkaczyk/eloquence#151]
Hello!
I need to get the initially mapping of already mapped fields back to insert them with a MSSQL Stored Procedure.

*Model*
```php
protected $maps = [
     'new_nice_name' => 'badOldname1',
];
```

*Controller*
```php
$model = new Model();
$model->fill($request->all());

// $model->toArray() has the new_nice_name, but I would need to the old name to be passed to the Stored Procedure
$this->db->select('StoredProcedureName', $model->toArray()); 
```

Any idea how to get the mapped field names with the content from the request?

Thanks!

**Comment by codedge** [comment]
It's working without issued by using `$model->getAttributes()`.

**Comment by DanielBoettner** [comment]
I get an empty return for that, as soon as I add ` $maps`
