### ISSUE TITLE
Using raw queries

### ISSUE THREAD

**Issue by baaskoen** [jarektkaczyk/eloquence#156]
Is it possible search on a value that has been selected using a raw query? For example the following query:

```
Product::where('company_id', $activeCompanyId)
            ->select(
                '*',
                \DB::raw('CONCAT(products.prefix, products.name, products.suffix) AS product_number')
            )
            ->whereActive()
            ->search($request->get('query'), ['search_name' => 10, 'product_number' => 10, 'description_1' => 8])
            ->get();
```

This query won't work. It will tell me the column `product_number` does not exist.

**Comment by jarektkaczyk** [comment]
`searchable` won't work in most cases like this, since it needs to recreate your query and build a subquery off it.
