### ISSUE TITLE
Larave 5.4

### ISSUE THREAD

**Issue by divdax** [jarektkaczyk/eloquence#159]
I think we need an update. :smile:

**Comment by nospoon** [comment]
+1 
Any chance we could have it for 5.4 please?

**Comment by DanEdney** [comment]
+1

**Comment by redroses** [comment]
Agreed. Looks like just an update to composer.json

**Comment by Sin30** [comment]
@redroses if that's the case, it should be fairly easy to update.

**Comment by linxun** [comment]
+1

**Comment by mjurkowski** [comment]
+1

**Comment by maig81** [comment]
+1

**Comment by nospoon** [comment]
It looks like the composer.json was updated quite a while ago to accept illuminate/database 5.4 (https://github.com/jarektkaczyk/eloquence/pull/152), but it seems that the composer repository has not been updated and it is still only accepts 5.3.

**Comment by maxvaser** [comment]
+1  - This is a great library!

**Comment by nospoon** [comment]
Just noticed, there is already a pull request waiting to be merged to fix the version requirement. Not sure why it's been sitting there for 28 days now.

**Comment by aaronsnyder** [comment]
+1 - @nospoon It looks like this change was merged, no? However, still the same result, unable to resolve illuminate\database dependency.

**Comment by nospoon** [comment]
@aaronsnyder The original PR to introduce 5.4 was indeed merged, however it contained an error (single | instead of ||), there is a second PR to correct that but this one still hasn't been merged (https://github.com/jarektkaczyk/eloquence/pull/155)

**Comment by AdrienPoupa** [comment]
I think sofa/hookable should be updated as well.

**Comment by Remo** [comment]
I had to create a fork for this, you can use `"ortic/eloquence": "~5.4"` till this gets merged. I will happily delete my fork once this has been fixed.

**Comment by Remo** [comment]
It seems like there's a problem now!
I'm running into this issue https://github.com/jarektkaczyk/eloquence/issues/21

**Comment by Remo** [comment]
I have no clue what I'm doing there, not enough experience regarding eloquent bindings, but I noticed that the values weren't passed into the query, this commit seems to fix things for me. I'm sure there's a better solution though
https://github.com/ortic/eloquence/commit/b9ddde95d4bb3692233687ef84cb7f3a2dc90d70

**Comment by Remo** [comment]
Sorry guys, this patch doesn't work. It's fine as long as you just call the `search` method, but it fails if you want to filter for another field.

**Comment by Shpartko** [comment]
+1

**Comment by lchogan** [comment]
+1

**Comment by BlueTeck** [comment]
+1

**Comment by dermatzeimnetz** [comment]
+1

**Comment by Remo** [comment]
it's not that simple, here's another issue we would have to take care of https://github.com/jarektkaczyk/eloquence/issues/166

**Comment by diego-vieira** [comment]
those interested on a working 5.4 version could should this repo:
https://github.com/ortic/eloquence

Currently I have sent PR with a couple of fixes.
Some tests are still failing. If someone could have a look at the tests and try to fix them that'd be great.

Current errors are

```
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /Users/diego/Projects/eloquence/phpunit.xml

...........................F..........E........................  63 / 152 ( 41%)
.............................................................E. 126 / 152 ( 82%)
..........................

Time: 1.08 seconds, Memory: 14.00MB

There were 2 errors:

1) Sofa\Eloquence\Tests\MappableTest::mapped_join_polymorphic_relation
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0_Illuminate_Database_ConnectionInterface::select("select "companies"."name" from "users" left join "companies" on "companies"."brandable_id" = "users"."id" and "brandable_type" = ? limit 1", array(0=>'UserMorph',), true). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/diego/Projects/eloquence/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1718
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1703
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1686
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1673
/Users/diego/Projects/eloquence/src/Mappable.php:333
/Users/diego/Projects/eloquence/src/Mappable.php:165
/Users/diego/Projects/eloquence/src/Mappable.php:139
/Users/diego/Projects/eloquence/src/Mappable.php:72
/Users/diego/Projects/eloquence/src/Mappable/Hooks.php:28
/Users/diego/Projects/eloquence/vendor/ortic/hookable/src/Pipeline.php:84
/Users/diego/Projects/eloquence/vendor/ortic/hookable/src/Pipeline.php:88
/Users/diego/Projects/eloquence/vendor/ortic/hookable/src/Hookable.php:245
/Users/diego/Projects/eloquence/vendor/ortic/hookable/src/Hookable.php:76
/Users/diego/Projects/eloquence/vendor/ortic/hookable/src/Builder.php:66
/Users/diego/Projects/eloquence/vendor/ortic/hookable/src/Builder.php:457
/Users/diego/Projects/eloquence/vendor/illuminate/database/Eloquent/Model.php:1316
/Users/diego/Projects/eloquence/tests/MappableTest.php:91

2) Sofa\Eloquence\Tests\SearchableBuilderTest::length_aware_pagination
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0_Illuminate_Database_ConnectionInterface::select("select count(*) as aggregate from (select `users`.*, max(case when `users`.`last_name` = ? then 150 else 0 end + case when `users`.`last_name` like ? then 50 else 0 end + case when `users`.`last_name` like ? then 10 else 0 end) as relevance from `users` where (`users`.`last_name` like ?) group by `users`.`primary_key`) as `users` where `relevance` >= 2.5", array(), true). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/diego/Projects/eloquence/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1718
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1703
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1803
/Users/diego/Projects/eloquence/vendor/illuminate/database/Query/Builder.php:1776
/Users/diego/Projects/eloquence/vendor/illuminate/database/Eloquent/Builder.php:1332
/Users/diego/Projects/eloquence/tests/SearchableBuilderTest.php:186

--

There was 1 failure:

1) Sofa\Eloquence\Tests\JoinerTest::it_joins_dot_nested_relations
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'select * from "users" inner join "profiles" on "users"."profile_id" = "profiles"."id" inner join "companies" on "companies"."morphable_id" = "profiles"."id" and "companies"."morphable_type" = ?'
+'select * from "users" inner join "profiles" on "users"."profile_id" = "profiles"."id" inner join "companies" on "companies"."morphable_id" = "profiles"."id" and "morphable_type" = ?'

/Users/diego/Projects/eloquence/tests/JoinerTest.php:38

FAILURES!
Tests: 152, Assertions: 207, Failures: 1, Errors: 2.
Script phpunit && ./vendor/bin/phpcs src --standard=psr2 --report=diff --colors handling the test event returned with error code 2
```

**Comment by Remo** [comment]
@diego-vieira this should fix the failure https://github.com/ortic/eloquence/pull/2
I wonder whether I should set up travis to properly check these things.
I'm not a big fan of forking, but better a maintained fork than a broken library.
What's the opinion about that here?

**Comment by diego-vieira** [comment]
@Remo indeed, but we can always merge your repo with this one as soon as @jarektkaczyk is back.

**Comment by ebbbang** [comment]
@Remo Made a pull request that would IMHO pass all Tests and errors ...

Would integrate in my project after your pull request and let you know how it goes ...

Feedback is much appreciated ...

**Comment by Remo** [comment]
Thanks, check this https://travis-ci.org/ortic/eloquence

**Comment by jarektkaczyk** [comment]
I will look into it ASAP. Thanks

Jarek Tkaczyk

softonsofa :: development with pleasure

**Comment by ebbbang** [comment]
Hey @jarektkaczyk , I made the PR on @Remo's repo ...
We have made a lot of changes. I would request @Remo to create a new PR on @jarektkaczyk's repo so he can check it out.

Thanks to @jarektkaczyk , @Remo , @diego-vieira for the great work ...

**Comment by maxvaser** [comment]
@jarektkaczyk have you been able to look at @remo's PR? It's been a month. It would great to get your awesome package working for Laravel 5.4.

**Comment by jarektkaczyk** [comment]
upgraded to 5.4 finally ;) https://github.com/jarektkaczyk/eloquence/tree/5.4

thanks to @Remo and everyone else who made effort, sorry it took so long

**Comment by maxvaser** [comment]
Thanks @jarektkaczyk!!! and for the subsequent quick bug fix!
