### ISSUE TITLE
Mapping on equal keys does nothing

### ISSUE THREAD

**Issue by codepilotde** [jarektkaczyk/eloquence#161]
Refactoring some old legacy code I found the following Problem:

Using a mapping array 
```
$maps = [
'new_key' => 'old_key2',
'old_key2' => 'old_key2'
]

```
I would expect that the setters for `setNewKeyAttribute() `is executed as well as the setter `setOldKey2Attribute()`. 
The acutal behavoir is that only` setNewKeyAttribute() `is executed.

Is that the intended behavior?

**Comment by jarektkaczyk** [comment]
edge case
