### ISSUE TITLE
Undefined make()

### ISSUE THREAD

**Issue by noprobz09** [jarektkaczyk/eloquence#162]
Hello,

I have error when I use this package on my sample search. The error says  "Call to a member function make() on null" :(

Below is my model:

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Sofa\Eloquence\Eloquence;


class Thesis extends Model
{
    use SoftDeletes;

    use Eloquence;

    
    protected $table = 'test_table';

    protected $searchableColumns = ['column1', 'column2'];



}
```

Any help is greatly appreciated!!!

**Comment by noprobz09** [comment]
Its like the error is on the vendor\sofa\Eloquence\src\Builder.php on line 77 :(

**Comment by IvanBernatovic** [comment]
Hi, you need to add `Sofa\Eloquence\ServiceProvider::class` to your service provider list in app/config/app.php.

**Comment by odahcam** [comment]
How can I use this outside of Laravel?

**Comment by odahcam** [comment]
Sorry. #18 got my back.
