### ISSUE TITLE
Incorrect logic of column listing in trait Eloquence

### ISSUE THREAD

**Issue by zhanghuanchong** [jarektkaczyk/eloquence#164]
The property $columnListing is static, while all the models will share it. But different model has different columns. We need to key them by table name, like this:
```php
$columnListing[$tableName] = $columnsInThisTable;
```

Looks methods "loadColumnListing", "getColumnListing" and "hasColumn" in Eloquence needs to be adjusted.

**Comment by jarektkaczyk** [comment]
hey, we don't need anything like this. However, being it `static` means, that you need to use `Eloquence` trait in each of the models (not in parent/base model), otherwise it indeed gets overriden by other models.

Might switch to instance context, but currently that's how it works.
