### ISSUE TITLE
L5.4 getJoinKeys breaking changes

### ISSUE THREAD

**Issue by bdanchilla** [jarektkaczyk/eloquence#166]
In Relations/Joiner.php https://github.com/jarektkaczyk/eloquence/blob/5.3/src/Relations/Joiner.php#L177

the method `getJoinerKeys`

calls the following methods that do not exist in Laravel 5.4

1.   `instanceof HasOneOrMany` calls `getForeignKey`
2.   `instanceof BelongsTo` calls `getQualifiedOtherKeyName`
3.   `instanceof BelongsToMany` calls `getOtherKey`

In Mappable.php 
https://github.com/jarektkaczyk/eloquence/blob/5.3/src/Mappable.php#L306

the method `getJoinerKeys`

calls the following methods that do not exist in Laravel 5.4

1.   `instanceof HasOne` calls `getForeignKey`
2.   `instanceof BelongsTo` calls `getQualifiedOtherKeyName`

**Comment by diego-vieira** [comment]
@bdanchilla this should fix it:
https://github.com/ortic/eloquence/pull/1

**Comment by jarektkaczyk** [comment]
https://github.com/jarektkaczyk/eloquence/tree/5.4
