### ISSUE TITLE
Mappable - Auto-Generated "Model::whereColumnName()" Functions

### ISSUE THREAD

**Issue by milsanore** [jarektkaczyk/eloquence#169]
Hi,
Firstly, thank you for the package, I think you've tackled a significant shortfall of Laravel. 

My existing database has a mix of snake_case and camelCase columns, and after implementing your package the following query (on a DB column called "seoAlias") now works:

$y = AdvertiserModel::where('seoAlias', '=', 'someValue')->get();

Which is brilliant. This query, however, does not:

$x = AdvertiserModel::whereSeoAlias('someValue')->get();

I just wanted to know whether or not your package targets these "auto-generated" functions or not.

Thank you,

**Comment by jarektkaczyk** [comment]
@milsanore Hey, no, the package doesn't handle that.

paraphrazing Freddy: _too much magic will kill you_

In other words - my humble suggestion to you and everyone *NEVER EVER* use this feature (along with a few more shipped with eloquent, like `appends` etc), unless you are the only one working on the project and you are 100% sure what you're doing and so on and so forth ... ;)
