### ISSUE TITLE
rightJoinRelations() does not pull custom attributes from relation object

### ISSUE THREAD

**Issue by levelel** [jarektkaczyk/eloquence#17]
#### Models:
Customer has many Addresses, and has one primary address defined in foreign-key column `primary_address_id`
Addresses belongs to one Customer

Customer has an attribute defined:
```php
public function getFullAddressAttribute()
{
    //get primary address's fullAddress attribute
    $address = Address::find($this->primary_address_id);
    if($address)
        return $address->fullAddress;
    //if customer does not have primary address defined, return a blank array []
    return [];
}
```
Addresses has an attribute with same name defined:
```php
public function getFullAddressAttribute()
{
    //get each line and combine into one array
    return [
            ($this->customer_id ? "To: ".$this->customer->name : ''),
            $this->line_1.',',                                    //lines are inserted with comma ',' and space ' '
            ($this->line_2 ? $this->line_2.', ' : ''),            //so that it should return something like:
            ($this->line_3 ? $this->line_3.', ' : ''),            //['123 main st., ', 'Apt 8F, ', 'Los Angeles, ' CA ', '90010 ']
            $this->city.', '.
            $this->province.' '.
            $this->zipcode.' '.
            $this->country
        ];
}
```
#### code:
Now I want to fetch a customer's addresses: 
```php
Customer::rightJoinRelations('addresses')->select('addresses.*')->where('customers.id', 2);
```
and it returs:
```json
{"id":2,"customer_id":2,"line_1":"28099 Nicolas Mill","line_2":"Apt. 964","line_3":null,"city":"Emardville","province":"CO","country":null,"zipcode":"14319-7111","phone":"","note":"Blanditiis aut vitae beatae blanditiis.","created_at":"2015-07-14 15:32:04","updated_at":"2015-07-14 15:32:04","fullAddress":[]}
```
From the results you can see it returns Addresses table columns fine, but notice at the end "fullAddress" is blank. However, in Address model, as you can see, there is no way it could return an empty array.

The other way around, if I want to fetch an address's customer, I do
```php
Address::rightJoinRelations('customer')->select('customers.*')->where('addresses.id', 2);
```
It returns Customers table columns fine, except "fullAddress" returns
```json
"fullAddress":["",",","","",",   "]
```
Notice it tried to insert the lines with comma and space, which should be done in Address model. The only situation this could happen is when in Customers table primary_address_id is defined, and the address it points to is all empty, which is not possible, as the fields are required in database and in model.
#### my guess:
So I guess the problem was that, rightJoinRelations fetches fullAddress from the model left to it, instead of the one on the right, even if I specified in `select('tableName.*')` clause.

**Comment by levelel** [comment]
Hello, is anyone watching?

**Comment by jarektkaczyk** [comment]
Not sure what the problem is. `right/leftJoinRelation` joins the table, that's all. All the eloquent features work just the same. I would need to see exactly what your logic does and how you are calling this accessor.

**Comment by levelel** [comment]
I've updated the post with details of the models and accessors. Please have a look.

@jarektkaczyk Thank you for you time.

**Comment by jarektkaczyk** [comment]
You're doing it wrong.

This
```
Customer::rightJoinRelations('addresses')->select('addresses.*')->where('customers.id', 2);
```

returns `Customer` eloquent model, but with `Address` fields, so it won't use the `getFullAddress` accessor defined on the `Address` model, but rather the one defined on the `Customer` model.

That said, this piece:
```
    $address = Address::find($this->primary_address_id);
```
is going to return `null` and the accessor returns `[ ]`.

When you're trying the other way around with `Address::rightJoinRelation(..)->select('customers.*')...` it does pretty much the same, but the other way around - calls `fullName` accessor on the `Address` model, but having `Customer` fields.


Now, I have no idea what you're trying to achieve, but it is definitely not the way. So let's start from the beginning - what is that you'd like to do?

**Comment by levelel** [comment]
@jarektkaczyk I see. I am simply trying to retrieve relation objects from a given item. For example, addresses of a given customer. 
I know there are other ways like `Customer::find(1)->addresses()->get()` but thought your repository provided an interesting alternative, so I decided to give a try. Anyway, thanks for your work. It's really awesome.

**Comment by jarektkaczyk** [comment]
It's not an alternative for the relations, but it rather complements them so you can easily perform some tasks, that would be cumbersome otherwise.
