### ISSUE TITLE
Searchable - formatting fields before searching?

### ISSUE THREAD

**Issue by andcl85** [jarektkaczyk/eloquence#171]
Hello, 

Is there a way to specify a format for the columns to be searched before calling `search()` method?

Imagine we want to search within a model with several date fields, **among others** (in typical dateTimeString MySQL format: `YYYY-mm-dd HH:ii:ss`). And also imagine that users search that dates specifying another, localized format, e.g.: `dd/mm/YYYY HH:ii:ss`. How would you manage this situation?

Pd. I can not preformat the dates (changing from localized to standard date format manually before searching) because full text search is algo performed on other model columns...

Thanks in advance.

**Comment by jarektkaczyk** [comment]
Please explain with example
