### ISSUE TITLE
searching doesn't work properly when used with tags

### ISSUE THREAD

**Issue by nowshad-sust** [jarektkaczyk/eloquence#172]
@jarektkaczyk 
I've got a post model which uses cviebrock\taggable for tagging posts.

my search configuration 
protected $searchableColumns = [
        'title',
        'description',
        'location',
        'user.name',
        'tags.name'
    ];

but, when I attach that 'tags.name' searching for tags works well, but searching for all other fields doesn't work properly. only works for the first word of the corresponding field.

example:
if title is "Job Fair" and I search with the keyword "fair", then it doesn't find anything when the 'tags.name' field is included to the searchable array. Otherwise all works pretty smoothly.
Thanks in advance.

**Comment by jarektkaczyk** [comment]
Try with 5.4 branch

**Comment by nowshad-sust** [comment]
@jarektkaczyk updated the package and now the whole thing is broken :(
check #175
