### ISSUE TITLE
updated from orctic/eloquence to sofa/eloquence 5.4, but getting error

### ISSUE THREAD

**Issue by nowshad-sust** [jarektkaczyk/eloquence#175]
@jarektkaczyk  Getting this error, when i'm trying to search on a single 'title' column of my 'posts' table.
It was working fine with orctic/eloquence
```
QueryException in Connection.php line 647:
SQLSTATE[HY000]: General error: 2031 (SQL: select count(*) as aggregate from (select `posts`.*, max(case when `posts`.`title` = ? then 15 else 0 end + case when `posts`.`title` like ? then 5 else 0 end + case when `posts`.`title` like ? then 1 else 0 end) as relevance from `posts` where (`posts`.`title` like ?) group by `posts`.`id`) as `posts` where `relevance` >= 0.25)
```

**Comment by jarektkaczyk** [comment]
thanks for feedback - try now, updated the version with latest fix for pagination.

**Comment by nowshad-sust** [comment]
@jarektkaczyk yes the #175 is resolved. But i've defined the searchable array as below -
 ```
protected $searchableColumns = [
        'title',
        'description',
        'location',
        'user.name',
        'tags.name'
    ];
```
And as before this issue is not solved yet.

**Comment by nowshad-sust** [comment]
@jarektkaczyk , i guess solved it playing with the threshold value.
great job, great package.
