### ISSUE TITLE
query()->getConnection() not working for laravel 5.4

### ISSUE THREAD

**Issue by sjmarve** [jarektkaczyk/eloquence#178]
To replicate the issue:
On a laravel 5.4 instance with eloquence, if you run:
`php artisan tinker` in terminal
then:
`use App\User`
then:
`User::query()->getConnection()`
you get something like: 
=> Sofa\Eloquence\Builder {#813}

instead of a connection object.
Something to do with the `Hookable@queryHook` method

**Comment by sw-double** [comment]
+1 It also breaks ModelFactory.
`factory(User::class)->create()`gives this error

```
BadMethodCallException: Call to undefined method Sofa\Eloquence\Query\Builder::getName()

/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2451
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1250
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:146
/vendor/laravel/framework/src/Illuminate/Support/Collection.php:260
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:149
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:129
```

**Comment by routegroup** [comment]
It's a bug in hookable jarektkaczyk/hookable#10

**Comment by svencoeck** [comment]
Thanks for the patch, routegroup. It's working fine.

**Comment by jarektkaczyk** [comment]
Added test to make sure it's not a problem anymore and closing
https://github.com/jarektkaczyk/eloquence-base/commit/93598ce1688bd9834332a6b9d1aa7c3d99002a2c
