### ISSUE TITLE
Deleting Meta Attributes

### ISSUE THREAD

**Issue by kamdhenu** [jarektkaczyk/eloquence#179]
It seems that even after deleting model the related meta attributes are not getting deleted from the "meta_attributes" table.

I tried and observed this on Laravel 5.4, having soft delete enabled on my model.

My Delete Function:
```
public function destroy($id)
    {
        $model= Model::find($id);

        if ($model->delete()) {
            $message = 'Model deleted successfully!';
            session()->flash('alert-success', $message);
            return response()->json(['status' => 'success', 'message' => $message]);
        }
    }
```

My Forece Delete Function:
```
public function trashDestroy($id)
    {
        $model= Model::onlyTrashed()->find($id);

        if ($model->forceDelete()) {
            $message = 'Model and all related data  deleted successfully!';
            session()->flash('alert-success', $message);
            return response()->json(['status' => 'success', 'message' => $message]);
        }

    }
```

**Comment by jarektkaczyk** [comment]
Indeed, meta attributes are not deleted in cascade by the package.

I wonder if using this one would sove your problem https://github.com/jarektkaczyk/eloquent-cascade

Otherwise a PR would be great, but mind that it's a BC breaking change, so make it optional
