### ISSUE TITLE
Error with Validable (Call to a member function make() on null)

### ISSUE THREAD

**Issue by dimitriSpb** [jarektkaczyk/eloquence#180]
Hi All,

I'm begining with Lumen and this package and I have an error when I try to use Validable.
I follow wiki : [https://github.com/jarektkaczyk/eloquence/wiki/Validable](url)

I have this error :
 _Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function make() on null in C:\xampp\htdocs\spb-api\vendor\sofa\eloquence\src\Validable.php:164
Stack trace:
#0 C:\xampp\htdocs\spb-api\vendor\sofa\eloquence\src\Validable.php(67): App\API\V1\Models\ApiModel->getValidator()_

So I try to debug in package to check if I missing a config to use correctly this package and I found line where I have a problem but don't know why.
In file _sofa/eloquence/src/Validable.php_ in function _bootValidable()_ line 54 
`public static function bootValidable()
    {
        static::observe(new Observer);

        if (!static::$validatorFactory) {//var_dump(app('validator'), app()->bound('queue'), app());
            if (function_exists('app') && app()->bound('validator')) {
                static::setValidatorFactory(app('validator'));
            }
        }
    }`
This return false : `app()->bound('validator')`
Maybe you know why ? 
When I do a dump of app() I see in property availablablekey validator
`public 'availableBindings' => 
    array (size=37)
      'auth' => string 'registerAuthBindings' (length=20)
      'auth.driver' => string 'registerAuthBindings' (length=20)
      'Illuminate\Auth\AuthManager' => string 'registerAuthBindings' (length=20)
      'Illuminate\Contracts\Auth\Guard' => string 'registerAuthBindings' (length=20)
      'Illuminate\Contracts\Auth\Access\Gate' => string 'registerAuthBindings' (length=20)
      'Illuminate\Contracts\Broadcasting\Broadcaster' => string 'registerBroadcastingBindings' (length=28)
      'Illuminate\Contracts\Broadcasting\Factory' => string 'registerBroadcastingBindings' (length=28)
      'Illuminate\Contracts\Bus\Dispatcher' => string 'registerBusBindings' (length=19)
      'cache' => string 'registerCacheBindings' (length=21)
      'cache.store' => string 'registerCacheBindings' (length=21)
      'Illuminate\Contracts\Cache\Factory' => string 'registerCacheBindings' (length=21)
      'Illuminate\Contracts\Cache\Repository' => string 'registerCacheBindings' (length=21)
      'composer' => string 'registerComposerBindings' (length=24)
      'config' => string 'registerConfigBindings' (length=22)
      'db' => string 'registerDatabaseBindings' (length=24)
      'Illuminate\Database\Eloquent\Factory' => string 'registerDatabaseBindings' (length=24)
      'encrypter' => string 'registerEncrypterBindings' (length=25)
      'Illuminate\Contracts\Encryption\Encrypter' => string 'registerEncrypterBindings' (length=25)
      'events' => string 'registerEventBindings' (length=21)
      'Illuminate\Contracts\Events\Dispatcher' => string 'registerEventBindings' (length=21)
      'files' => string 'registerFilesBindings' (length=21)
      'hash' => string 'registerHashBindings' (length=20)
      'Illuminate\Contracts\Hashing\Hasher' => string 'registerHashBindings' (length=20)
      'log' => string 'registerLogBindings' (length=19)
      'Psr\Log\LoggerInterface' => string 'registerLogBindings' (length=19)
      'queue' => string 'registerQueueBindings' (length=21)
      'queue.connection' => string 'registerQueueBindings' (length=21)
      'Illuminate\Contracts\Queue\Factory' => string 'registerQueueBindings' (length=21)
      'Illuminate\Contracts\Queue\Queue' => string 'registerQueueBindings' (length=21)
      'Psr\Http\Message\ServerRequestInterface' => string 'registerPsrRequestBindings' (length=26)
      'Psr\Http\Message\ResponseInterface' => string 'registerPsrResponseBindings' (length=27)
      'translator' => string 'registerTranslationBindings' (length=27)
      'url' => string 'registerUrlGeneratorBindings' (length=28)
      'validator' => string 'registerValidatorBindings' (length=25)
      'Illuminate\Contracts\Validation\Factory' => string 'registerValidatorBindings' (length=25)
      'view' => string 'registerViewBindings' (length=20)
      'Illuminate\Contracts\View\Factory' => string 'registerViewBindings' (length=20)`

And if I remove this false condtion, all works, so why don't return me true ?

This is a part of my code if you need it to help me 
Models 

`use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;
use Sofa\Eloquence\Validable; // extension trait
use Sofa\Eloquence\Contracts\CleansAttributes;
use Sofa\Eloquence\Contracts\Validable as ValidableContract;

class ApiModel extends Model implements ValidableContract, CleansAttributes
{
    use Eloquence, Mappable, Validable;`

`class Campaign extends ApiModel
{`
...
protected static $businessRules = [
        'title_campaign'  => 'required|min:5', // rules passed as pipe-separated string
        'email_sender' => ['required', 'email', 'unique:users'] // or as an array
    ];

    protected static $dataIntegrityRules = [
        'email_sender' => 'max:255' // or as an array
    ];
    // You can also pass custom attribute names and validation messages
    // just like when using Laravel Validator directly.
    protected static $validationAttributes = [
        'email_sender' => 'EMAIL SENDER',
        'title_campaign'  => 'TITRE CAMPAGNE',
    ];

    protected static $validationMessages = [
        'required'       => 'Man, field :attribute must be filled!',
        'email.required' => 'Man, gimme your email?!',
    ];
`

Controller 

`$a = Campaign::getCreateRules();
        Campaign::getValidatedFields();
        new Campaign() ;
        $camp->email_sender = 'invalid';
        $camp->title_campaign = 'foo';
        $camp->isValid(); //Error HERE
        $camp->getValidationErrors()->all();`

And I declare ServiceProvider in app.php
`$app->register(\Sofa\Eloquence\ServiceProvider::class);`

Running with : Lumen (5.4.6) (Laravel Components 5.4.*)

Thanks

**Comment by dimitriSpb** [comment]
I find a solution but I don't think it's the good way, in bootsrapp/app.php, I add this line 
`app('validator');`

If you have better/proper solution , can you tell me ? :)

Thanks

**Comment by jarektkaczyk** [comment]
Anyone with PR will be welcome. I'm don't intend to work on lumen compatibility.
