### ISSUE TITLE
Error in SQL query when relevance threshold is not full number

### ISSUE THREAD

**Issue by bonny** [jarektkaczyk/eloquence#181]
I was getting sql errors when using a query like this:

```
    $events2 = CrimeEvent::search($s, [
        "parsed_title" => 20,
        "parsed_title_location" => 10
    ])->paginate(10);
```

but not when using a query like this:

```
    $events2 = CrimeEvent::search($s, [
        "parsed_title" => 20,
        "parsed_title_location" => 20
    ])->paginate(10);
```

After some digging I found that the query that caused errors ended like this:

    where `relevance` >= 7,5 order by `relevance` desc

while the working one ended like

    where `relevance` >= 10 order by `relevance` desc

[MySQL use “.” as a decimal separator](https://dev.mysql.com/doc/refman/5.6/en/number-literals.html) but 7,5 uses a comma, so I think this is a bug.

**Comment by jarektkaczyk** [comment]
@bonny `,` is never used as decimal separator - maybe you provided it somewhere as threshold in this form.

**Comment by bonny** [comment]
Hi again! 

I looked at this some more and I think the reason for this is that I use a Swedish locale. Sweden (among with many other countries) uses decimal comma and not decimal point as the decimal mark. So when a float is casted to a string the current locale determines if a comma or a dot is used.

Quick example:

        // calculated threshold from buildSubquery()
        $threshold = 15.5;
        
        // outputs "15.5"
        echo $threshold;
        
        // change to swedish locale
        setlocale(LC_ALL, 'sv_SE', 'sv_SE.utf8');
        // outputs "15,5"
        echo $threshold;

This could be solved in addSearchClauses() by using `number_format()` in the where condition, making the $threshold always use a dot as the decimal mark:

    $this->query->where('relevance', '>=', new Expression(number_format($threshold, 1)));

**Comment by jarektkaczyk** [comment]
fixed in https://github.com/jarektkaczyk/eloquence-base/tree/5.6.1
