### ISSUE TITLE
Boolean fulltext search

### ISSUE THREAD

**Issue by seanarce** [jarektkaczyk/eloquence#184]
Hi Great work pretty much what I wanted for my app, I just have couple of concerns, when I'm searching on a field with value that is separated by comma, e.g` | foo, bar, bazz |`, how should my query look for if I want to search for "bar"? do you support boolean search?

**Comment by jarektkaczyk** [comment]
Hey, nope.
Searchable is an easy way to add search functionality, without `fulltext` index support. These days you could implement search engine easily, so I'm not planning any improvements here.
