### ISSUE TITLE
what if fields names are contained in another table?

### ISSUE THREAD

**Issue by KONEY** [jarektkaczyk/eloquence#188]
Not sure I can call this an issue but it's not clear if it's somehow possible to map fields to a different source, in my scenario another table containing fields name (with per ID relationship).

**Comment by jarektkaczyk** [comment]
Yes, you can.
Check relation mapping here https://github.com/jarektkaczyk/eloquence/wiki/Mappable

Although it is pure magic and I do not recommend it, unless it's small and only yours project :)
