### ISSUE TITLE
different rule does not work when 1 field is null

### ISSUE THREAD

**Issue by ziming** [jarektkaczyk/eloquence#19]
Hi,

Upon saving I had an issue with save returning false. Upon calling getValidationErrors

It told me that it failed a validation rule where 2 field need to be different.

In this case 1 of my field is null, and another is an integer. So it is indeed different and should pass validation.

Given that it passes the FormRequests but fails at save(). Hence I decide to file the issue here.

**Comment by jarektkaczyk** [comment]
@ziming Hey, I need to see your code. Apparently these 2 values are not properly assigned on the model.

If one of these fields is not in fact an attribute, then don't define it on the model, but rather add it to the request rules.
