### ISSUE TITLE
Other models can not be created or updated from within another Models event.

### ISSUE THREAD

**Issue by dlnandrsn** [jarektkaczyk/eloquence#190]
When attempting to create a new model from within another models event, validation will always fail and the new model cannot be saved.

Both models extend a common base model, the base model contains the Validable contract/trait.

Sounds similar to issue #84 and possibly #16?

**Comment by jarektkaczyk** [comment]
Add traits to each model rather than the base model and, more importantly, don't update models from other models' events - it's a `goto` hidden behind nicely looking event system. That's not how events work, that's not how you want to update your data.

This is my humble opinion ;)
