### ISSUE TITLE
Specifying A Select Clause Alias not working

### ISSUE THREAD

**Issue by fuzzdis** [jarektkaczyk/eloquence#191]
I have a model (User as example) with Eloquence & Mappable enabled.

The following query is working at laravel version 5.4.17
$user = User::select('name as username', 'mail as usermail')->first();
and I can access the attribute via $user->username.

When I upgrade the laravel framework to 5.4.22
the query is not working anymore, it can be executed successfully, but the aliases are not in effect, that mean I can't rename the colume name through select clause. After I remove the Eloquence & Mappable traits from my User Model, the select alias work again.

btw, The User Model itself has a blank $maps property.

**Comment by jarektkaczyk** [comment]
I'm guessing this is the reason:
https://github.com/laravel/framework/compare/v5.4.17...v5.4.22#diff-cc3d43e01028390141596ae0da939930R282 

unfortunately Laravel core doesn't give a shit about any BC so things like that just happen. If you're willing to provide a PR fixing the issue, I will gladly take a look and merge.
Cheers!
