### ISSUE TITLE
toArray using maps if exists

### ISSUE THREAD

**Issue by guilherup** [jarektkaczyk/eloquence#193]
Looking to find a way to find this feature on Mappable trait.

Usage is for override toArray and get the columns as they where defined on $maps array.

```php
public function toArray()
{
    $values = $this->attributesToArray();
    if (isset($this->maps)) {
        $flip = [];
        $flip = array_flip($this->maps);
        foreach ($values as $key => $value) {
            if (isset($flip[$key])) {
                $values[$flip[$key]] = $value;
                unset($values[$key]);
            }
        }
    }
    return array_merge($values, $this->relationsToArray());
}
```

I build this part code to address this return a I was expecting of return.

This feature aready exists and I don't know how to use?

Thanks! This Mappable it's awesome!

**Comment by jarektkaczyk** [comment]
Is there anything I should address?

**Comment by DanielBoettner** [comment]
He seemed to have the same issue as I do.
After filling a model I cant get the Attributes as a bulk when a map was set.
