### ISSUE TITLE
Trait method newEloquentBuilder has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by aletundo** [jarektkaczyk/eloquence#197]
I'm using `5.4.1` version of your package together with `grimzy/laravel-mysql-spatial:^1.0`.
I thought the error in the title was fixed using:
 `use SpatialTrait {
      Eloquence::newEloquentBuilder insteadof SpatialTrait;
      SpatialTrait::newEloquentBuilder as newEloquentSpatialBuilder;
    }`
because the Eloquence methods I'm using works well.

But now, I'm trying to update the location field of my model using the `Point` class of the other package without success. The exeception is: `SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field`. It is related to the `newEloquentBuilder` method which is not called probably.

Any idea to fix this collision without impact on the functionalities? I really need both packages.
I'm going to open an issue to Laravel Mysql Spatial package too.

**Comment by jarektkaczyk** [comment]
I can suggest creating a hook with this functionality:

https://github.com/grimzy/laravel-mysql-spatial/blob/master/src/Eloquent/Builder.php

or making sure that you actually pass `"ST_GeomFromText('".$geometry->toWKT()."')"` rather than simple string values.
