### ISSUE TITLE
Expression's string casting can cause a comma in the value sent to DB query

### ISSUE THREAD

**Issue by gbaudoin** [jarektkaczyk/eloquence#198]
https://github.com/jarektkaczyk/eloquence/blob/fcc6415b21f099cca18eb6311aa6817328597a60/src/Builder.php#L146

When using setLocale() with a locale that has a comma as separator, new Expression($threshold) could be casted as "0,75", causing a DB error.

**Comment by bonny** [comment]
I think this is the same as or at least related to this one that I reported:
https://github.com/jarektkaczyk/eloquence/issues/181

**Comment by jarektkaczyk** [comment]
fixed in https://github.com/jarektkaczyk/eloquence-base/tree/5.6.1

@bonny thanks for the effort, sorry it took almost a year ;)
