### ISSUE TITLE
Collision problems between Trait

### ISSUE THREAD

**Issue by RomainLanz** [jarektkaczyk/eloquence#2]
Hey,

So I said on my last PR (https://github.com/jarektkaczyk/eloquence/pull/1) we have a problem because we have both rewrite `setAttribute` method.

I can create a PR on the Laravel repository to allow some hook in Eloquent's process. But if it's rejected, we need to create a new Trait to allow hooks in Eloquent.

What do you think of that?

**Comment by jarektkaczyk** [comment]
I'm thinking of the best way to do that using extensions/macros w/o polluting the core `Model` class. So we just decorate that thing.

**Comment by RomainLanz** [comment]
Why not create our model named `Eloquence` and extend the real Eloquent Model?

It's simple and easy to implement.

**Comment by jarektkaczyk** [comment]
resolved - check 0.3 branch

**Comment by RomainLanz** [comment]
Looking awesome :+1:
