### ISSUE TITLE
Lumen

### ISSUE THREAD

**Issue by tr33m4n** [jarektkaczyk/eloquence#20]
Hello there,

Just wondering whether anyone has got this working with Lumen at all? Just tried using it, no errors are being thrown, but then again the desired functionality is not working either. This is my model:

    <?php 

    namespace App\Models;

    use Illuminate\Database\Eloquent\Model;
    use Sofa\Eloquence\Eloquence;
    use Sofa\Eloquence\Mappable;

    class Customers extends Model
    {
        use Eloquence, Mappable;

        protected $maps = [
            'CUS_UNIQUE' => 'id'
        ];

    protected $table = 'ASC_CUS_TBL_OLD';

    protected $fillable = [
        'id',
        'name',
        'contacts',
        'addresses',
        'credit_limit'
    ];

Any ideas?
Cheers

**Comment by tr33m4n** [comment]
Never mind, I appear to have got Mapping working which is all the functionality I need right now, thanks :)

**Comment by jarektkaczyk** [comment]
@tr33m4n So was it some error on your part? There shouldn't be any problem with lumen.

**Comment by tr33m4n** [comment]
Yeah, I made an error, all good now, thanks

**Comment by sant0ro** [comment]
How did you get working?

Here i'm using lUmen and can't make it work.
