### ISSUE TITLE
`[ErrorException] Invalid argument supplied for foreach()` in factory (using Mappable)

### ISSUE THREAD

**Issue by lennonmb** [jarektkaczyk/eloquence#201]
When I run seeder with factory I got this error:

`[ErrorException] Invalid argument supplied for foreach()`

I solved it when temporary I removed Mappable traits from Models. But I think this is not a good way. It would be hard to comment/uncomment traits of all Models every time just to be able to seed. Maybe is there another way?

**Comment by jarektkaczyk** [comment]
Show stacktrace and your setup. This error doesn't tell us anything ;)

**Comment by lennonmb** [comment]
Sorry for not answer early. First I want to apologyze for my bad English. 

Well, I found the error, and it happens in create method in model because I was using methods in __construct to dinamically add maps attributes. I'm using Rebing/GraphQL and I needed something like this:

User model:

```
protected $maps =[
"friendly_name"=>"unfriendly_name",
...
"users.friendly_name"=>"unfriendly_name", //"table_name.attribute_name". 
...
];
```

In some models I use a lot of attributes, it wouldn't be a good practice to copy and paste and add table name to every attribute, so I did this:

```
protected $table="users";
protected $maps;
protectes $appends;

public function __construct($attributes=[]){
       parent::__construct($attributes);
        $maps =[
           "friendly_name"=>"unfriendly_name",
            ...
       ];
        $tbmaps = [];
        foreach ($maps as $key => $map) {
            $tbmaps["$this->table." . $key] = $map;
        }

        $this->maps = array_merge($maps, $tbmaps);
}
```

When I call getMaps() method in Users it works fine:

```
$user=new User();
$user->getMaps();
//["friendly_name"=>"unfriendly_name", ... , "users.friendly_name"=>"unfriendly_name", ...];
```

But when I used create() method it returned

`[ErrorException] Invalid argument supplied for foreach() in factory (using Mappable) in vendor... mappable.php on line 456 `

(Line was obtained when I used create method, in seeder I didn't get the line, the issue title error was all what I got in seeder)

This is the method in that line:

```
  protected function parseMappings()
    {
        $this->mappedAttributes = [];

        foreach ($this->getMaps() as $attribute => $mapping) { //this is the line
            if (is_array($mapping)) {
                $this->parseImplicitMapping($mapping, $attribute);
            } else {
                $this->mappedAttributes[$attribute] = $mapping;
            }
        }
    }
```

In that method $this->getMaps() didn't return the maps, just returned null. It would be a POO thing, I guess. Well, this is the solution I used in this case:

```
protected $table="users";
protected $maps=[
           "friendly_name"=>"unfriendly_name",
            ...
       ];

public function __construct($attributes=[]){
       parent::__construct($attributes);

        $tbmaps = [];
        foreach ($this->maps as $key => $map) {
            $tbmaps["$this->table." . $key] = $map;
        }
        $this->maps = array_merge($this->maps, $tbmaps);
}
```

It works fine in create and seed.
