### ISSUE TITLE
Search seems to ignore certain words, like Cat, Chicken

### ISSUE THREAD

**Issue by DeanWard** [jarektkaczyk/eloquence#204]
I'm searching company names and if one has something like Cat or Chicken in it, you can't find them by searching for those words.

I've run like queries on the database manually and results are being returned.

Search looks like this

`$query->search($value,[
					'long_id',
					'company.name',
					'company.tradingAddress.postcode',
					'company.registeredAddress.postcode',
					'company.phone',
					'company.email',
					'company.website',
					'company.contacts.first_name',
					'company.contacts.last_name',
					'company.contacts.phone',
					'company.contacts.mobile'
				]);`
Thanks

**Comment by jarektkaczyk** [comment]
there's no reason for certain words to be ignored
