### ISSUE TITLE
Mappable via Mutable not working in 5.5

### ISSUE THREAD

**Issue by dvantage** [jarektkaczyk/eloquence#206]
After update on Laravel 5.5 Mutable is not working.

```php
namespace App\Models;


use DB;
use Illuminate\Database\Eloquent\Model;

use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;
use Sofa\Eloquence\Mutable;


/**
 * Class Apps
 *
 * @package App\Models
 */
class Apps extends Model
{

    use Eloquence, Mappable, Mutable;


    protected $getterMutators = [
        'name' => 'strtolower'
    ];

    /**
     * Таблица заявок (DEMANDS)
     *
     * @var string
     */
    protected $table = 'hl_demands';

    protected $maps = [
        'id'     => 'ID',
        'oldId'  => 'UF_OLD_ID',
        'active' => 'UF_ACTIVE',
        'name'   => 'UF_NAME',
    ];
}
```

```php
$appData = Apps::find(311757);

$appData->id;
$appData->name;
```

"message": "Call to a member function mutate() on null",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/dev4/www/laravel/vendor/sofa/eloquence-mutable/src/Mutable.php",
    "line": 89,

**Comment by agonzalezml** [comment]
I have also this issue, any news about that?

**Comment by vladamir** [comment]
+1
I can't save any data if just add `use Eloquence` to Model. Eloquence v5.5.1, Laravel v5.5.21.
Method save() returns true, but data not updating and UPDATE-query not perfoming. And this shit on my production!

Code is simple: 
```
$p = Post::find(2);
$p->views = 3432;
$r = $p->save()
```
```
use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;

class Post extends Model
{
    use Eloquence;
    public $timestamps = false;
    protected $table = 'posts';
}
```

If I comment the line `use Eloquence`, all data will be updated. What's wrong?

**Comment by kevdotbadger** [comment]
Solution at the end of https://github.com/jarektkaczyk/eloquence/issues/205

**Comment by bionicmaster** [comment]
I have made a PR to solve this, I'm waiting for this to be integrated to eloquence-mutable.
https://github.com/jarektkaczyk/eloquence-mutable/pull/1

in the meantime this is available in bionicmaster/eloquence and bionicmaster/eloquence-mutable
