### ISSUE TITLE
Using eloquence in standalone mode?

### ISSUE THREAD

**Issue by yamilrevilla** [jarektkaczyk/eloquence#208]
Hi folks, thanks for the hard work done here!
My question is, I'm using Eloquent ORM in standalone mode (outside Laravel) so can I use Eloquence package as well?

I did not try to install the package because I saw the "Register the service provider" section in the documentation.

PD: Sorry for my english mistakes, if I have any 😃

**Comment by jarektkaczyk** [comment]
Sorry for late reply.
Yes, you can use it standalone.
