### ISSUE TITLE
leftJoinRelation not creating correct query when using relation with hasManyThrough

### ISSUE THREAD

**Issue by grasmanek94** [jarektkaczyk/eloquence#209]
User model:

	<?php
	
	namespace App;
	
	use Illuminate\Notifications\Notifiable;
	use Illuminate\Foundation\Auth\User as Authenticatable;
	use Sofa\Eloquence\Eloquence;
	
	class User extends Authenticatable
	{
		use Eloquence;
		use Notifiable;
	
		/**
		 * The attributes that are mass assignable.
		 *
		 * @var array
		 */
		protected $fillable = [
			'device_id', 'name'
		];
	
		public function Scores()
		{
			return $this->hasMany(UserScore::class);
		}
	
		public function UnlockCodes()
		{
			return $this->hasManyThrough(UnlockCode::class, UserScore::class, 'user_id', 'id', 'id', 'unlock_code_id');
		}
	}

UserScore model:

	<?php
	
	namespace App;
	
	use Illuminate\Database\Eloquent\Model;
	
	class UserScore extends Model
	{
		protected $fillable = [
			'user_id', 'unlock_code_id'
		];
	
		public function UnlockCode()
		{
			return $this->belongsTo(UnlockCode::class);
		}
	
		public function User()
		{
			return $this->belongsTo(User::class);
		}
	}

UnlockCode model:

	<?php

	namespace App;

	use Illuminate\Database\Eloquent\Model;

	class UnlockCode extends Model
	{
		protected $fillable = [
			'code', 'data', 'is_level_unlock', 'description'
		];

		public function UserScores()
		{
			return $this->hasMany(UserScore::class);
		}

		public function Users()
		{
			return $this->hasManyThrough(User::class, UserScore::class, 'unlock_code_id', 'id', 'id', 'user_id');
		}

		static public function Random()
		{
			$arr = ['A', 'B', 'C', 'D', 'E', 'F', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
			$res = "";
			for($i = 0; $i < 41; ++$i)
			{
				$res .= $arr[rand(0, count($arr))];
			}

			return $res;
		}
	}

Using in the code:

		$users = User::leftJoinRelations('UnlockCodes')
			->groupBy('users.id')
			->selectRaw('users.*, count(unlock_codes.id) as unlock_count')
			->orderBy('unlock_count','desc')
			->take(30)
			->get();

Output query is: 

	select users.*, count(unlock_codes.id) as unlock_count from `users` left join `user_scores` on `user_scores`.`user_id` = `users`.`id` left join `unlock_codes` on `unlock_codes`.`id` = `user_scores`.`id` group by `users`.`id` order by `unlock_count` desc limit 30

But output query should be:

	select users.*, count(unlock_codes.id) as unlock_count from `users` left join `user_scores` on `user_scores`.`user_id` = `users`.`id` left join `unlock_codes` on `unlock_codes`.`id` = `user_scores`.`unlock_code_id` group by `users`.`id` order by `unlock_count` desc limit 30

Bug is in 
	`unlock_codes`.`id` = `user_scores`.`id`
where it should be
	`unlock_codes`.`id` = `user_scores`.`unlock_code_id`

**Comment by jarektkaczyk** [comment]
Thanks for the detailed report.

As `hasManyThrough` is an edge case for me, I have no plans to work on this one.
Feel free to drop a PR if you like :surfing_man:
