### ISSUE TITLE
Error with Searchable trait

### ISSUE THREAD

**Issue by tr33m4n** [jarektkaczyk/eloquence#21]
Hello there,

I added the searchable columns to my model and added "Customer::search($string)->get();" to my controller, however I'm encountering the following error:

"SQLSTATE[HY000]: General error: 8120 General SQL Server error: Check messages from the SQL Server [8120] (severity 16) [(null)] (SQL: select * from (select [ASC_CUS_TBL_OLD].*, max(case when [ASC_CUS_TBL_OLD].[CUS_INV_NAME] = OAKWOOD then 15 else 0 end + case when [ASC_CUS_TBL_OLD].[CUS_INV_NAME] like OAKWOOD% then 5 else 0 end + case when [ASC_CUS_TBL_OLD].[CUS_INV_NAME] like %OAKWOOD% then 1 else 0 end) as relevance from [ASC_CUS_TBL_OLD] where ([ASC_CUS_TBL_OLD].[CUS_INV_NAME] like %OAKWOOD%) group by [ASC_CUS_TBL_OLD].[CUS_UNIQUE]) as [ASC_CUS_TBL_OLD] where [relevance] >= 0.25 order by [relevance] desc)"

I'm using sqlsrv for the database driver.

Any ideas?
Thanks

**Comment by tr33m4n** [comment]
Hmm, never mind... Adding created_at and updated_at to the $maps and removing them from $hidden appears to have fixed it

**Comment by tr33m4n** [comment]
Why was this closed? I added a comment earlier but then deleted it as I was mistaken. This is still an issue

**Comment by jarektkaczyk** [comment]
So show some errors. It's hard to help without any details.

**Comment by tr33m4n** [comment]
Sorry it's taken me ages to get back... Basically it seems to be an issue with how the query is formed and using a MS SQL backend... This is the response from the server:
```sql
"SQLSTATE[HY000]: General error: 8120 General SQL Server error: Check messages from the SQL Server [8120] (severity 16) [(null)] (SQL: select * from (select [ASC_COR_TBL].*, max(case when [ASC_COR_TBL].[COR_UNIQUE] = 1 then 15 else 0 end + case when [ASC_COR_TBL].[COR_UNIQUE] like 1% then 5 else 0 end + case when [ASC_COR_TBL].[COR_UNIQUE] like %1% then 1 else 0 end + case when [ASC_COR_TBL].[COR_CUSTOMER_CODE] = 1 then 15 else 0 end + case when [ASC_COR_TBL].[COR_CUSTOMER_CODE] like 1% then 5 else 0 end + case when [ASC_COR_TBL].[COR_CUSTOMER_CODE] like %1% then 1 else 0 end + case when [ASC_COR_TBL].[COR_ORDER_WHEN] = 1 then 15 else 0 end + case when [ASC_COR_TBL].[COR_ORDER_WHEN] like 1% then 5 else 0 end + case when [ASC_COR_TBL].[COR_ORDER_WHEN] like %1% then 1 else 0 end) as relevance from [ASC_COR_TBL] where ([ASC_COR_TBL].[COR_UNIQUE] like %1% or [ASC_COR_TBL].[COR_CUSTOMER_CODE] like %1% or [ASC_COR_TBL].[COR_ORDER_WHEN] like %1%) group by [ASC_COR_TBL].[COR_UNIQUE]) as [ASC_COR_TBL] where [relevance] >= 0.75 order by [relevance] desc)"
```
Do you reckon this is an error with the searchable trait or an error in the database driver?

**Comment by wislem** [comment]
Having the exact same issue. When I either define or use inline searchableColumns, I get the same General error (on MySQL)

Here's a e.g. for a pages table, using just `slug` as a the searchableColumn:

```SQLSTATE[HY000]: General error: 2031 (SQL: select count(*) as aggregate from (select `pages`.*, max(case when `pages`.`slug` = ? then 150 else 0 end + case when `pages`.`slug` like ? then 50 else 0 end + case when `pages`.`slug` like ? then 10 else 0 end + case when `pages`.`title` = ? then 135 else 0 end + case when `pages`.`title` like ? then 45 else 0 end + case when `pages`.`title` like ? then 9 else 0 end) as relevance from `pages` where (`pages`.`slug` like ? or `pages`.`title` like ?) group by `pages`.`id`) as `pages` where `relevance` >= 4.75 order by `relevance` desc)```

**Comment by wislem** [comment]
Moving the query over to my mysql manager and replacing the ? sign properly, the query works fine. So I suppose the problem lies there somewhere?

```sql
SELECT
	count(*) AS AGGREGATE
FROM
	(
		SELECT
			`pages`.*, max(
				CASE
				WHEN `pages`.`slug` = 'hom' THEN
					150
				ELSE
					0
				END + CASE
				WHEN `pages`.`slug` LIKE '%hom' THEN
					50
				ELSE
					0
				END + CASE
				WHEN `pages`.`slug` LIKE 'hom%' THEN
					10
				ELSE
					0
				END + CASE
				WHEN `pages`.`title` = 'hom' THEN
					135
				ELSE
					0
				END + CASE
				WHEN `pages`.`title` LIKE '%hom' THEN
					45
				ELSE
					0
				END + CASE
				WHEN `pages`.`title` LIKE 'hom%' THEN
					9
				ELSE
					0
				END
			) AS relevance
		FROM
			`pages`
		WHERE
			(
				`pages`.`slug` LIKE '%hom%'
				OR `pages`.`title` LIKE '%hom%'
			)
		GROUP BY
			`pages`.`id`
	) AS `pages`
WHERE
	`relevance` >= 4.75
ORDER BY
	`relevance` DESC
```

**Comment by jarektkaczyk** [comment]
@wislem Show me the code you execute. It's pagination I guess?

The query is surely OK, the problem lies in the way Laravel handles query bindings - db querying changed a bit in L5 and some issues appeared.

**Comment by wislem** [comment]
I'm not using pagination. I'm integrating the www.jquery-bootgrid.com plugin.

# Page Model
```php
class Page extends Model
{
    use Eloquence;

    protected $searchableColumns = [
        'slug' => 8,
        'title' => 10,
        'content' => 9
    ];

    protected $fillable = ['slug', 'title', 'content', 'meta_desc', 'is_active'];

}
```

# PageContoller@grid
```php
    public function grid(Request $request)
    {
        $take = ($request->has('rowCount')) ? $request->get('rowCount') : 10;
        $skip = $request->get('current') - 1;
        $searchPhrase = ($request->has('searchPhrase')) ? $request->get('searchPhrase') : '';
        $sort = ($request->has('sort')) ? $request->get('sort') : false;

        $results = $this->page->search($searchPhrase); //$this->page was injected at __construct
        $count_results = $results->count();
        $results = $results->take($take)->skip($take * $skip);

        if(is_array($sort)) {
            $results = $results->orderBy(key($sort), $sort[key($sort)]);
        }

        $results = $results->get();

        $rows = [];

        foreach($results as $row) {
            $rows[] = [
                'id' => $row->id,
                'slug' => $row->slug,
                'title' => $row->title,
                'is_active' => $row->is_active
            ];
        }

        $data = array(
            'current' => (int) $request->get('current'),
            'rowCount' => $take,
            'rows' => $rows,
            'total' => $count_results,
        );

        return response($data);
    }
```

**Comment by jarektkaczyk** [comment]
@wislem Please paste a dump of the query:
```
$results = $this->page->search($searchPhrase); //$this->page was injected at __construct
\DB::enableQueryLog();
$results->take(1)->get();
dd(\DB::getQueryLog());
```

**Comment by wislem** [comment]
```php
array:2 [
  0 => array:3 [
    "query" => "select column_name from information_schema.columns where table_schema = ? and table_name = ?"
    "bindings" => array:2 [
      0 => "aggekrit_db"
      1 => "pages"
    ]
    "time" => 3.0
  ]
  1 => array:3 [
    "query" => "select * from (select `pages`.*, max(case when `pages`.`slug` = ? then 120 else 0 end + case when `pages`.`slug` like ? then 40 else 0 end + case when `pages`.`slug` like ? then 8 else 0 end + case when `pages`.`title` = ? then 150 else 0 end + case when `pages`.`title` like ? then 50 else 0 end + case when `pages`.`title` like ? then 10 else 0 end + case when `pages`.`content` = ? then 135 else 0 end + case when `pages`.`content` like ? then 45 else 0 end + case when `pages`.`content` like ? then 9 else 0 end) as relevance from `pages` where (`pages`.`slug` like ? or `pages`.`title` like ? or `pages`.`content` like ?) group by `pages`.`id`) as `pages` where `relevance` >= 6.75 order by `relevance` desc limit 10 offset 0"
    "bindings" => array:12 [
      0 => "hom"
      1 => "hom%"
      2 => "%hom%"
      3 => "hom"
      4 => "hom%"
      5 => "%hom%"
      6 => "hom"
      7 => "hom%"
      8 => "%hom%"
      9 => "%hom%"
      10 => "%hom%"
      11 => "%hom%"
    ]
    "time" => 2.0
  ]
]
```

**Comment by Remo** [comment]
@wislem this is fairly old, sorry for bringing this up again, but did you ever find a solution to this? I've got the exact same problem. Query is fine when executed manually, but ran through laravel I get an error.

**Comment by wislem** [comment]
@Remo Unfortunately there was solution to this one. I just stopped using the trait :/

**Comment by Remo** [comment]
thanks @wislem not exactly what I wanted to hear ;-) but appreciate your quick answer!
