### ISSUE TITLE
PHP Error:  Call to a member function mutate() on null in [...]/sofa/eloquence-mutable/src/Mutable.php on line 89

### ISSUE THREAD

**Issue by BrekiTomasson** [jarektkaczyk/eloquence#210]
Just upgraded from 5.4 to 5.5 after every external package that I rely on seemed stable enough, and I'm still getting this error that I've seen people talk about in issues like #205, #206, jarektkaczyk/hookable#15, etc.

The error message I'm getting is the one in the subeject line, and the line in question is the return statement below:

    protected function mutableMutate($key, $value, $dir)
    {
        $mutators = $this->getMutatorsForAttribute($key, $dir);

        return static::$attributeMutator->mutate($value, $mutators);
    }

Any ideas what might (still) be wrong here?

**Extra info**: I added a simple `print_r()` on both $value and $mutators before the return statement and get this:

value: 311013700
mutators: intval

None of them are null, so the problem must be in the mutate method itself?

**Comment by bionicmaster** [comment]
I have made a PR to solve this, I'm waiting for this to be integrated to eloquence-mutable.
https://github.com/jarektkaczyk/eloquence-mutable/pull/1

in the meantime this is available in bionicmaster/eloquence and bionicmaster/eloquence-mutable

**Comment by jarektkaczyk** [comment]
@bionicmaster thank you for the PR.

Has been merged and tagged :+1:
