### ISSUE TITLE
Memory issue on long running commands

### ISSUE THREAD

**Issue by ragingdave** [jarektkaczyk/eloquence#212]
There seems to be a memory issue in relation to eloquence when in long running scripts. As an example case, using this library with the Mappable trait in conjunction with Laravel Scout causes a runaway memory condition.

**Comment by jarektkaczyk** [comment]
Thanks for headsup!

In general this package is pure magic on top of out-of-the-box magic of Eloquent itself.
There's cost to that magic and it doesn't scale well indeed.
If you could narrow down the issue in conjuction with scout, that would be great. I personally don't use them both and don't have such memory issues, so I have to rely on the cases reported by users.

:surfing_man:
