### ISSUE TITLE
Searchable doesn't work when using multiple counts 

### ISSUE THREAD

**Issue by FilipQL** [jarektkaczyk/eloquence#213]
When there are [multiple counts](https://laravel.com/docs/5.4/eloquent-relationships#counting-related-models) like this:

```
                ->withCount([
                    'comments',
                    'comments AS approved_comments' => function ($query) {
                        $query->where('approved', true);
                    },
                    'comments AS pending_comments' => function ($query) {
                        $query->where('approved', false);
                    }
                ])
```
... _Searchable_ doesn't work. For example, this will not work:

```
            $articles = $category->articles()
                ->search($q)
                ->withCount([
                    'comments',
                    'comments AS approved_comments' => function ($query) {
                        $query->where('approved', true);
                    },
                    'comments AS pending_comments' => function ($query) {
                        $query->where('approved', false);
                    }
                ])
                ->with(['user', 'category'])
                ->latest()
                ->paginate(15);

            dd($articles);
```
There are no errors, but there are no search results:

![1](https://user-images.githubusercontent.com/18264428/35062662-3857f836-fbc5-11e7-9952-960856f3db0c.png)

But when I remove _multiple counts_ and have just this:

```
            $articles = $category->articles()
                ->search($q)
                ->with(['user', 'category'])
                ->latest()
                ->paginate(15);
```
... it works fine, there are results:

![2](https://user-images.githubusercontent.com/18264428/35062764-7b6578b0-fbc5-11e7-9f50-2366e17b9738.png)

I am using **sofa/eloquence v5.5.1** and **Laravel 5.4**

**Comment by daverdalas** [comment]
Hey, I also had a problem with that. From what I remember, it was about assigning bad values for bindings in Laravel. I managed to fix it by overwriting the withCount method. Here you will find it: https://gist.github.com/daverdalas/ae6db2187d5d4a02890756bbb8530890

**Comment by FilipQL** [comment]
@daverdalas Thanks. I also saw that there are other issues with this package, especially when using with Laravel 5.4+... I wonder if this package is not maintained anymore.

**Comment by jarektkaczyk** [comment]
This is not supported due to the fact that `withCount` is using `joins` while searchable queries dynamically created subquery.
