### ISSUE TITLE
Empty result set when querying more than 4 related tables

### ISSUE THREAD

**Issue by sunnyjayjay** [jarektkaczyk/eloquence#215]
$items = Line::search($request->search, ['title','category','tags.tag','artist.organisation'])->get();

Gives a result set (15 in my case).

    $items = Line::search($request->search, ['title','category','tags.tag','artist.organisation','groups.title'])->get();

Gives an empty result set.

**Comment by jarektkaczyk** [comment]
I guess some `joins` there mess up the result.
As searchable is supposed to address simple use-cases, for such a thing I recommend using more robust 3rd party searching engine or custom-made queries.

**Comment by emiliogrv** [comment]
Hi, sorry for this comment, but @sunnyjayjay here is the solution: https://github.com/jarektkaczyk/eloquence/issues/53#issuecomment-175069781
