### ISSUE TITLE
Searching multiple models

### ISSUE THREAD

**Issue by kasperbisgaard** [jarektkaczyk/eloquence#216]
Hi,
I have a scenario where i have to search multiple models. Is that possible?
This is the case where there are multiple user_profile types.
A user hasOne of either UserProfile, AgencyProfile or ProfessionalProfile.

**Comment by jarektkaczyk** [comment]
Yes, use dot notation.

Check the last example here:
https://github.com/jarektkaczyk/eloquence/wiki/Builder-searchable-and-more#searchable
