### ISSUE TITLE
Support Laravel 5.6

### ISSUE THREAD

**Issue by vladamir** [jarektkaczyk/eloquence#217]
Will be compatibility with version Laravel 5.6? I can't update my project

**Comment by marcoocram** [comment]
Related https://github.com/jarektkaczyk/eloquence-base/pull/1

**Comment by freekmurze** [comment]
We'd like to use this too in L5.6

Do you have an ETA when L5.6 will come?

**Comment by jdavidbakr** [comment]
Yes, this is one of the last packages I need to have 5.6 support.  Is it just a matter of updating the dependencies or is there a larger issue underneath it?

**Comment by odahcam** [comment]
@jarektkaczyk we are all waiting. :/

**Comment by jarektkaczyk** [comment]
Any volunteer for a PR maybe? :)

If no one comes up with it, I will do it after I'm back from a trip with children.

**Comment by odahcam** [comment]
Doesn't https://github.com/jarektkaczyk/eloquence-base/pull/1 solves that? 😟

**Comment by jarektkaczyk** [comment]
Yes, looking into it right now. If just tagging 5.6 is enough, then 10mins and will be done
thanks

**Comment by jarektkaczyk** [comment]
DONE!
