### ISSUE TITLE
Excluding softly deleted related records (which use SoftDelete trait)

### ISSUE THREAD

**Issue by maqduni** [jarektkaczyk/eloquence#220]
I have the following query:

```
$query = Word::with([
            'spellings',
        ]);
$query->search(mb_strtolower(trim($value)), [
            'spellings.value' => 2,
        ], true);
```

Some of the spellings are softly deleted with `deleted_at` value not equal to `NULL`. The query still searches across these records.

How can I exclude them?

**Comment by jarektkaczyk** [comment]
Yes, it seems that `Relations\Joiner` doesn't take traits into consideration.

Could you provide a failing test here? 
https://github.com/jarektkaczyk/eloquence-base/blob/master/tests/JoinerTest.php

**Comment by maqduni** [comment]
Added a PR https://github.com/jarektkaczyk/eloquence-base/pull/2, please  take a look.

**Comment by jarektkaczyk** [comment]
Thanks, it has been merged and tagged.

I'm a bit concerned about this change being BC breaking, but at the same time it IS the expected behaviour for any eloquent query.

thanks

**Comment by maqduni** [comment]
Thank you!
