### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::search()

### ISSUE THREAD

**Issue by ajimatahari** [jarektkaczyk/eloquence#222]
i have followed all the steps... one by one... but the builder::search() keep undefined, i'm using laravel 5.4

**Comment by jarektkaczyk** [comment]
make sure to add `Eloquence` to your model and call search on Eloquent query, rather than `DB::table()...`.

here's info: https://github.com/jarektkaczyk/eloquence/wiki/Builder-searchable-and-more
