### ISSUE TITLE
SelectRaw and Eloquence search

### ISSUE THREAD

**Issue by vertoo** [jarektkaczyk/eloquence#224]
Hi,
I don't know, this is bug or my fault. When I use search and selectRaw (also whereRaw) with bindings parameters are messed.
Parts of my code:
```php
$services->search($filters['term'], [
    'name'              => 50,
    'description'       => 30,
]);

$parameters      = [
    $filters['lng'],
    $filters['lat'],
];
$parametersWhere = [
    $filters['lng'], // -2.0316291
    $filters['lat'], // 52.4813037
    $filters['distance'], // 8
];
$services->selectRaw('ST_Distance_Sphere(point(lng, lat),point(?, ?)) * 0.00621371192 as distance', $parameters);
if ($filters['distance'] > 0) {
    $services->whereRaw('ST_Distance_Sphere(point(lng, lat),point(?, ?)) * 0.00621371192 < ?', $parametersWhere);
}
```
This generate just one query (count = 0) because where have bad bindings:
```sql
where `relevance` >= 62.50 
and ST_Distance_Sphere(point(lng, lat),point('-2.0316291', '52.4813037')) * 0.00621371192 < '-2.0316291'
```
should be `< 8`

But when I change user variable `$parametersWhere` in select bindings where statement is ok.
In this case second query for results is wrong. Bad bindings.
```sql
select *, ST_Distance_Sphere(point(lng, lat),point('sandwell', 'sandwell%')) * 0.00621371192 as distance 
from (select `services`.*, max(case when `services`.`name` = '%sandwell%' 
then 750 else 0 end + case when `services`.`name` like 'sandwell' 
then 250 else 0 end + case when `services`.`name` like 'sandwell%' 
then 50 else 0 end +
-- (...)
where `relevance` >= 62.50 
and ST_Distance_Sphere(point(lng, lat),point('8', '-2.0316291')) * 0.00621371192 < '52.4813037' 
order by `relevance` desc limit 10 offset 0
```
As you can see in where in point are bad values, in select point are bad values (keyword). 

I think is something wrong with order of bindings but I can't find where. Someone had same issue?

Laravel v5.5.39 - I will update it today,
Eloquence Base v5.6.2 (same problems with 5.5)

**Comment by jarektkaczyk** [comment]
Unfortunately `whereRaw`/`selectRaw` might not work as expected as searchable is running a subquery under the hood and it needs to apply all the PDO bindings manually. 
You may want to change the order, ie. `$query->selectRaw()->whereRaw()->search()` - not sure if it helps though.
