### ISSUE TITLE
Possible to only implement the basic search functionalities?

### ISSUE THREAD

**Issue by CrixuAMG** [jarektkaczyk/eloquence#225]
I'm working on a project in which we require to perform search queries on multiple models.
On one of the models, the `hasTranslations` trait is applied, and is conflicting with this package (the base version also conflicts).
The conflicting method (could be more than one) is `setAttribute`.

So, the question is like the title states, is it possible to only implement the basic search functionalities?

**Comment by jarektkaczyk** [comment]
you need `eloquence-base` for search, but it comes with the basic functionality and `setAttribute` is included there.
