### ISSUE TITLE
Call to undefined method Sofa\Eloquence\Query\Builder::withDefault()

### ISSUE THREAD

**Issue by tedsecretsource** [jarektkaczyk/eloquence#228]
Love the plugin, really terrific in most cases. Unfortunately, I've got a requirement to use withDefault() and it's not working.

**Summary**

Laravel throws 

> BadMethodCallException: Call to undefined method Sofa\Eloquence\Query\Builder::withDefault()

 when adding `->withDefault()` to `hasMany()` inside a model.

**Preconditions**
- Eloquence 5.6
- Laravel 5.5

**Steps to Reproduce**
1. Create a model
2. Create a hasMany relationship definition, e.g.:
```php
public function opportunities () {
    return $this->hasMany('App\Models\Opportunity');
}
```
3. Add `->withDefault()` to the relationship definition so that you can have default values in your relationship and views don't fail.

**Expected Result**
- The site loads normally

**Actual Result**
- Exception: BadMethodCallException: Call to undefined method Sofa\Eloquence\Query\Builder::withDefault()

**Workaround**
- create a custom override of sofa/Eloquence and define your own withDefault()???

**Reference**
https://laravel.com/docs/5.5/eloquent-relationships#default-models

**Comment by jarektkaczyk** [comment]
Hi,
while I understand the temptation to use it like
![image](https://user-images.githubusercontent.com/6928818/41806754-3918e1ac-76f6-11e8-8a97-93404138ea93.png)


it is very bad idea and I personally won't work on it.
Why, you may ask? It's like me saying to you _bro, go and jump from this roof. you're gonna have great fun! ...for 2 seconds, then you die_ - you don't want me do that :smile: 

If you're willing to add it as a PR, I'm gonna merge it though.

**Comment by tedsecretsource** [comment]
Thanks for the follow-up.

> it is very bad idea

Actually I would argue that it is a good idea as it implements the [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern). That said, I totally understand your point of view. I'll have a look and see if I can provide a PR (but, not terribly likely due solely to a lack of time!)

Thanks a lot for the rest of the code, though. Very, very helpful (and so far working really well)!

**Comment by jarektkaczyk** [comment]
@tedsecretsource I definitely don't want to argue ;)

What I mean is that it is misleading and using I discourage `$model->relation` (or, god forbid `$model->relation->another->yet_another_relation`) in views in general. Unless you're the one-man army working on a small project, this is very brittle.

What I recommend instead is using null object explicitly, not by eloquent's magic. `withDefault` is not null object pattern and let's not mix `Java` infamous `NULL pointer exception` with it.

Might be unpopular opinion in laravel's world though :man_shrugging:

**Comment by tedsecretsource** [comment]
Argue? Me neither! That's just a form of speech…

To be clear, I'm not using that in the view (god no!). I'm defining the relationship in the model. Adding `withDefault()` guarantees I'll have something to work with instead of having to use `if` statements. It's not a perfect solution but, at the very least, the result will be a blank view rather than a 500 error.

In any case, don't worry about it. I'll see if I can pop together a PR. Thanks!
