### ISSUE TITLE
when i not define $SearchableColumns in model and set fulltext = false or true ,  nothing effected or can't search exact keyword!

### ISSUE THREAD

**Issue by miadz** [jarektkaczyk/eloquence#229]
when i not define $SearchableColumns in model and set fulltext = false or true ,
 nothing effected or can't search exact keyword!
i change getSearchableColumns function on trait and its work!

laravel 5.5
eloquence 5.6

    public function getSearchableColumns()
    {
//        return (property_exists($this, 'searchableColumns')) ? self::getColumnListing() : [];

//my change
        return (property_exists($this, 'searchableColumns')) ? $this->searchableColumns : self::getColumnListing();
    }

**Comment by jarektkaczyk** [comment]
This is current code, so I'm guessing it's not valid issue anymore, right?

![image](https://user-images.githubusercontent.com/6928818/41806685-7536e2d4-76f5-11e8-8b58-3eedae72389a.png)
