### ISSUE TITLE
Timestamps not being mapped

### ISSUE THREAD

**Issue by tr33m4n** [jarektkaczyk/eloquence#24]
Hello there,

I'm currently facing an issue with timestamps not being updated in the database. I've mapped them as follows:
```php
protected $maps = [
	    'id' => 'CUS_UNIQUE',
	    'name' => 'CUS_INV_NAME',
        'email' => 'CUS_EMAIL_ADD',
        'customer_id' => 'CUS_CODE',
        'created_at' => 'CUS_CREATED',
        'updated_at' => 'CUS_UPDATED'
];
```
I would imagine that the timestamps that get created automatically would map to the columns I've specified? Perhaps there's something else happening here that's causing the issue

Any ideas?
Cheers
Dan

**Comment by jarektkaczyk** [comment]
For future reference: timestamps need to be handled by default eloquent constants:
```
const CREATED_AT = 'CUS_CREATED';
const UPDATED_AT = 'CUS_UPDATED';
```
