### ISSUE TITLE
[Search] Ambiguous columns in 1-2 relations

### ISSUE THREAD

**Issue by Lykegenes** [jarektkaczyk/eloquence#25]
Let's say a Match has 2 Teams. (Two BelongsTo relations to the same table)
I want to search on firstTeam.name and secondTeam.name
```php
protected $searchableColumns = ['firstTeam.name', 'secondTeam.name'];
```

The resulting sql is : 
```sql
SELECT *
FROM matchs
LEFT JOIN teams ON matchs.firstTeam_id = teams.id
LEFT JOIN teams ON matchs.secondTeam_id = teams.id
```

The search logic will be applied twice, both times on "teams.name", which is ambiguous.

The resulting sql should be : 
```sql
SELECT *
FROM matchs
LEFT JOIN teams AS firstTeam ON matchs.firstTeam_id = firstTeam.id
LEFT JOIN teams AS secondTeam ON matchs.secondTeam_id = secondTeam.id
```

Simply set an alias to every duplicated table, using it's Laravel relation name, firstTeam and secondTeam in this case.

What do you think?

**Comment by jarektkaczyk** [comment]
Sounds good, a PR maybe?

**Comment by Lykegenes** [comment]
I had some time to start working on it. There are many use cases, but your tests pretty much cover them all, which will make things easier (thanks!). Here's a quick draft I made if you want to take a look : 
lykegenes@139d378933c73d7f205aa126e5ec3496d3801b1c

I'll make the PR when all tests pass!
