### ISSUE TITLE
Just a small remark: that strtolower on email is a VeryBadExample(tm)

### ISSUE THREAD

**Issue by HenkPoley** [jarektkaczyk/eloquence#253]
Used here: https://github.com/jarektkaczyk/eloquence/wiki/Mutable

Since the local-part (before the `@`) of an email is in principle defined as case-sensitive.

See [RFC 5321 2.4](https://tools.ietf.org/html/rfc5321#section-2.4).

> The local-part of a mailbox MUST BE treated as case sensitive.

**Comment by jarektkaczyk** [comment]
thanks, PR to readme would be perfect!
