### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by crlcu** [jarektkaczyk/eloquence#255]
Hi,
Is this package still maintained?

**Comment by PeraMika** [comment]
I also asked the same (**a year ago**): https://github.com/jarektkaczyk/eloquence-base/issues/7 
I don't know what to say, this package still not compatible with Laravel 6.x (https://github.com/jarektkaczyk/eloquence/issues/251) :/ 
It seems the answer is: No (damnit)

**Comment by jarektkaczyk** [comment]
yeah
