### ISSUE TITLE
Laravel 7 Update

### ISSUE THREAD

**Issue by seewhy17** [jarektkaczyk/eloquence#256]
is there any hope of a Laravel 7 update?

**Comment by ahmad-saad** [comment]
Hallo @jarektkaczyk ,

I just download the packages und try it with illuminate/database 7.4 with the latest version by Lumen und it works without problem.

so I think you just need to accept the illuminate/database version 7 in your sofa/eloquence-base composer and then it will work.

can you do this, and then let us report a new issues if there are any??

thanks

**Comment by ahmad-saad** [comment]
Hallo @seewhy17 

I create a temp package in

https://packagist.org/packages/enbit/eloquence

it use the namespace as the orignal package.

I didn't change anything I just accept the version 7 as I  said in the last comment.

you can use it until the owner make his changes.

Regard's

**Comment by seewhy17** [comment]
> https://packagist.org/packages/enbit/eloquence

Thanks @ahmad-saad can I pull in the just searchable extension via 
```composer require enbit/eloquence-searchable```

**Comment by ahmad-saad** [comment]
Hallo @seewhy17 ,

eloquence-base now support laravel 7 you can simply use the @jarektkaczyk package.

as I said my package was a Temp package until he apply the changes.

for more info see

https://github.com/jarektkaczyk/eloquence-base/issues/24#event-3230553215
