### ISSUE TITLE
[SUPPORT] Laravel 7 concerns

### ISSUE THREAD

**Issue by studmon** [jarektkaczyk/eloquence#257]
As the owner has gone silent, I'll share a couple of fixes for the errors I encountered when upgrading to Laravel 7.x. Hope this will help others struggling to get it rolling.

**ERROR** Sofa\Hookable\Builder - when using `where(function ($q) {...})` in query builder was creating subquery instead of parameter grouping.
**How I fixed it:**
```
Sofa\Hookable\Builder::where(...)
// Change if in the method to
if (!in_array(strtolower($operator), $this->operators, true)) {
           // Copied from Illuminate\Database\Eloquent\Builder
            if ($column instanceof Closure && is_null($operator)) {
                $column($query = $this->model->newQueryWithoutRelationships());

                $this->query->addNestedWhereQuery($query->getQuery(), $boolean);
            } else {
                list($value, $operator) = [$operator, '='];
            }
        }
```

**ERROR** Sofa\Eloquence\Builder - `Call to undefined function Sofa\Eloquence\ends_with()`
**How I fixed it:**
Replacing helper methods with Str method calls.
Sofa\Eloquence\Builder:
```
use Illuminate\Support\Str;
...
Str::endsWith(...)
```

**ERROR**: Call to a member function make() on null
**How I fixed it:**
Add `Sofa\Eloquence\BaseServiceProvider::class,` to config/app.php

**Comment by jarektkaczyk** [comment]
tagged new version, thans
