### ISSUE TITLE
Package already exists

### ISSUE THREAD

**Issue by kirkbushell** [jarektkaczyk/eloquence#31]
Hi there!

Just letting you know that the term Eloquence has been in use as a package name (my own) for a while, check it out. Basically just provides some basic extensions since Laravel 4.x. It's very similar in the sense that it's Laravel based, and is built to work with Eloquent.

https://github.com/kirkbushell/eloquence

Adding this here as some may get confused.

**Comment by jarektkaczyk** [comment]
Yes, I noticed, but it was too late for renaming. These 2 don't duplicate any behaviour I guess anyway.

**Comment by kirkbushell** [comment]
Too late? Rhumsaa renamed his UUID package which is the most popular one in PHP, long after people were using it.

**Comment by jbrooksuk** [comment]
FWIW this is the point in namespaces. `kirkbushell/eloquence` is different to `jarektkaczyk/namespace`.

**Comment by kirkbushell** [comment]
That's not really the point.

**Comment by jbrooksuk** [comment]
Yeah, I agree that a different name would've been better, sure. A little research would've helped, but because of namespaces, it doesn't actually matter when adding a package :)

**Comment by kirkbushell** [comment]
Exactly - namespacing isn't the issue, and never was. It's the fact that the package is identically named and is an extension to the same library - it can be confusing.

**Comment by jbrooksuk** [comment]
Okay, that we agree on :)
