### ISSUE TITLE
Validable validator Factory error

### ISSUE THREAD

**Issue by edgaralves** [jarektkaczyk/eloquence#34]
My validator Factory is not being set because in the src/Validable:162
`if (function_exists('app') && isset(app()['validator'])) {`
Although the app()['validator'] has the Factory, the isset allways returns false.

I'm using Lumen, in a PHP5.6.10 env

**Comment by jarektkaczyk** [comment]
@edgaralves Please try using `isset(app('validator'))` instead and let me know if that helps.

**Comment by jarektkaczyk** [comment]
Does it happen when you try `isset(app()['validator'])` somewhere else in the code?

**Comment by edgaralves** [comment]
`isset(app('validator'))` doesn't work because i can't use isset in a function call.

It happens everywhere else in the code.

**Comment by pashamesh** [comment]
+1

I'm using Lumen, in a PHP 5.5.9 env
