### ISSUE TITLE
Collection::keyBy with Mappable

### ISSUE THREAD

**Issue by sarahkemp** [jarektkaczyk/eloquence#38]
Is it expected that the Collection method keyBy() would not work with Mappable columns?

I have: 

    class Person extends Model
    {
        use Eloquence, Mappable;

        protected $table = 'SLSMAN',
            $primaryKey = 'SISM#',
            $connection = 'ibmi',
            $maps = [
                'first_name' => 'SIFNAM',
                'last_name' => 'SILNAM'
            ];
        ...

And:
    
    $people = Person::get()->keyBy('first_name');

But my collection only has one item in it and the key is an empty string. Using the original field name (like SIFNAM) returns the expected collection with items keyed by first name. Is this the expected behavior for Mappable?

Thanks for reading.

**Comment by jarektkaczyk** [comment]
It is not expected, intended, nor does it work like this on my end :)

Please make sure you're doing everything right, because I just tried and `keyBy` works just fine.

**Comment by sarahkemp** [comment]
I will investigate my code more carefully then, thank you for your response.

**Comment by sarahkemp** [comment]
For any future readers who might encounter my error (unlikely) - the problem was that I had an additional, incorrect map in my $maps property:

   $maps = ['first_name' => 'SIFNAM',
                  'last_name' => 'SILNAM',
                  'full_name' => ['SIFNAM', ' ', 'SILNAM'] // <- this is a problem
    ];

A little leftover code from my misunderstanding of the documentation of implicit and explicit field mapping failed quietly and caused quite a bit of confusion. With the full_name element in the $maps array, my keyBy worked for fields of numeric data type only, and it worked for both the original and mapped field name. However, all of my strings fields presented as empty when used for the keyBy, even when I put them in a closure (regardless of whether I used the original or mapped name). Removing the bad mapping fixed the problem. 

Thank you again for the plugin and your time @jarektkaczyk.
