### ISSUE TITLE
How to use Pagination with eloquence search

### ISSUE THREAD

**Issue by smmuthu** [jarektkaczyk/eloquence#41]
Hi @jarektkaczyk 

I have used your eloquence search with my Laravel 5.1 application. It performing well with my requirement so thanks for the great module. But I have struggled to use the pagination with this module can  you please help me to use pagination class with this?

Thanks.

**Comment by mattvb91** [comment]
What issues are you having with it? If you have the traits set up along with the serviceProvider you can just use:

```
Model::search($term)->paginate(10);
```

**Comment by smmuthu** [comment]
Thanks for your reply @mattvb91 . It works for me :-)

**Comment by mattvb91** [comment]
No problem. Remember to close the issue if you can.
