### ISSUE TITLE
PDOexception with migrating the MetaAttributesTable (MySql) ...

### ISSUE THREAD

**Issue by hardkiffeur** [jarektkaczyk/eloquence#5]
Hi,
Under fresh install, Type de serveur: MySQL - Version du serveur: 5.5.37-0ubuntu0.13.10.1 - (Ubuntu),
I've an error

  [Illuminate\Database\QueryException]                                         
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'm  
  eta_value' used in key specification without a key length (SQL: alter table  
   `meta_attributes` add index meta_attributes_meta_key_meta_value_index(`met  
  a_key`, `meta_value`))                                                       
                                         
  [PDOException]                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'm  
  eta_value' used in key specification without a key length

I just create the migration file and copie paste the migration sample from sofa/eloquence/src/Metatable/CreateMetaAttributesTable.php without the namespace ....

What sorte of meta_value table could I try to test Eloquence\Metable ?

**Comment by jarektkaczyk** [comment]
@hardkiffeur Just skip the index for now. I will take a look at this.

**Comment by hardkiffeur** [comment]
Serveur: Localhost via UNIX socket
Type de serveur: MySQL
Version du serveur: 5.5.37-0ubuntu0.13.10.1 - (Ubuntu)
Version du protocole: 10
Utilisateur: root@localhost
Jeu de caractères du serveur: UTF-8 Unicode (utf8)

Apache/2.4.6 (Ubuntu)
Version du client de base de données: libmysql - 5.5.37
Extension PHP: mysqli Documentation

**Comment by RomainLanz** [comment]
Dear @jarektkaczyk, @hardkiffeur,

If we read the MySQL documentation ([MySQL CREATE INDEX Syntax](https://dev.mysql.com/doc/refman/5.0/en/create-index.html)) we can read:
> BLOB and TEXT columns also can be indexed, but a prefix length must be given. 

But according to the article [MySQL Error 1170 (42000): BLOB/TEXT Column Used in Key Specification Without a Key Length](http://www.mydigitallife.info/mysql-error-1170-42000-blobtext-column-used-in-key-specification-without-a-key-length/)...
> MySQL doesn’t support limit on TEXT or BLOB.

They provide as solution to remove TEXT or BLOB column from the index constraint.

What do you think @jarektkaczyk?

**Comment by jarektkaczyk** [comment]
@RomainLanz Yes, that's the problem. I suppose raw statement will be the only way for now. Gonna take care of it soon.

**Comment by alexeitav** [comment]
Hi @jarektkaczyk ...take a look on this (http://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length).

"The solution to the problem is to remove the TEXT or BLOB column from the index or unique constraint, or set another field as primary key. If you can’t do that, and wanting to place a limit on the TEXT or BLOB column, try to use VARCHAR type and place a limit of length on it."

Could it be the problem?

**Comment by RomainLanz** [comment]
Your post has been written in 2009 and send a solution written in 2007. MySQL has change now.

If you look at the documention you can create an INDEX on TEXT or BLOB columns, but we need to put a length. Another solution is to completly remove the INDEX, but your performance will be worse.

As a workarround, you should try to add the index with `DB` Facade.

**Comment by jarektkaczyk** [comment]
Thanks guys, it's been already solved. I just didn't push it yet.
