### ISSUE TITLE
Query builder uses wrong decimal delimiter

### ISSUE THREAD

**Issue by InToSSH** [jarektkaczyk/eloquence#52]
Hi, I am using Searchable in my model and I specified these columns:
```
    protected $searchableColumns = [
        'translations.title' => 10,
        'variants.sku' => 20,
       
    ];
```
However as it calculates the relevance as 7.5 it uses comma as delimiter instead of a dot.
We are using comma in our country, so the server config is set to this value, however I think the Query Builder should make sure to use the dot no matter how the system is set.
The query looks like this:
```
select count(*) as aggregate from (select `items`.*, max(case when `item_translations`.`title` = stul then 150 else 0 end + case when `item_translations`.`title` like stul% then 50 else 0 end + case when `item_translations`.`title` like %stul% then 10 else 0 end + case when `item_variants`.`sku` = stul then 300 else 0 end + case when `item_variants`.`sku` like stul% then 100 else 0 end + case when `item_variants`.`sku` like %stul% then 20 else 0 end) as relevance from `items` left join `item_translations` on `item_translations`.`item_id` = `items`.`id` left join `item_variants` on `item_variants`.`item_id` = `items`.`id` where (`item_translations`.`title` like %stul% or `item_variants`.`sku` like %stul%) group by `items`.`id`) as `items` where `relevance` >= 7,5)
```
Also I am not sure how it handles the queries, for example when I search for `"stul a kleste"` it produces
``` 
...
`item_translations`.`title` = stul a kleste then 150 else 0
...
``` 
I think there should be quotation marks around it to make it more query safe, or is MySQL clever enough to figure it out for each example?
I am not exactly sure if it's a problem in your package, or in Laravel's QueryBuilder though, didn't go through the code to find out how it makes the queries.

Thank you.

**Comment by jarektkaczyk** [comment]
1 comma vs. dot should be handled on your server
2 it is escaped by PDO, the query simply looks like this for readability (it's the way Laravel shows it).
