### ISSUE TITLE
Searching seems to not work when more than 4 searchableColumns

### ISSUE THREAD

**Issue by lchogan** [jarektkaczyk/eloquence#53]
Everything works well if I have less than 4 searchableColumns. As soon as I have more than 4 searchable columns the search does not behave as expected. 

If I have a field with the value "This is a test" and I query with a string "test" the search works great as long as I have less than 4 searchable columns defined on the model. As soon as I have more than 4 searchable columns the search will not work as "test" (returns 0 results) but it will work if I search "is a test". 

**This returns a result**

*The model:*

    protected $searchableColumns = ['name','building_phone', 'manager_phone', 'manager_email', 'street_address', 'city', 'postal_code', 'country', 'instructions', 'user.first_name', 'user.last_name'];

*The controller:*

    $term = "is a test";    
    $buildings = Building::search($term)->paginate(10);

**This returns no results**

*The model:*

    protected $searchableColumns = ['name','building_phone', 'manager_phone', 'manager_email', 'street_address', 'city', 'postal_code', 'country', 'instructions', 'user.first_name', 'user.last_name'];

*The controller:*

    $term = "test";    
    $buildings = Building::search($term)->paginate(10);

**This returns results**

*The model:*

    protected $searchableColumns = ['name','building_phone', 'manager_phone', 'manager_email'];

*The controller:*

    $term = "test";    
    $buildings = Building::search($term)->paginate(10);

Any ideas? Thanks so much.

**Comment by jarektkaczyk** [comment]
@lchogan Try `Building::search($term, null, true, 0)->get()`

The last param `0` is threshold that needs to be exceeded by the record in order to show in the result. By default it is calculated like here: https://github.com/jarektkaczyk/eloquence/blob/5.2/src/Builder.php#L105

If that helps simply adjust the threshold to suit your needs.

**Comment by lchogan** [comment]
@jarektkaczyk That did help! It didn't work initially when I tried ````Building::search($term, null, true, 0)->get()```` But when I adjusted it to ````Building::search($term, null, true, 1)->get()```` things seemed to work well. Thanks for the quick reply.
