### ISSUE TITLE
Results of two tables

### ISSUE THREAD

**Issue by Giregar** [jarektkaczyk/eloquence#59]
Hey,
I've got two tables: tasks and tags.
tasks: id, title, text
tags: id, task_id, tag_name

How to merge the results of the two tables.
At the end, I want to display a task with the belonging tags.

**Comment by bobbybouwmann** [comment]
This is basic Laravel stuff that can be found in the documentation. You need to setup your relations and you can then query the tasks with the tags like so
```
$tasks = Task::with('tags')->get();
```
> Documentation: https://laravel.com/docs/master/eloquent-relationships
