### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bart** [jarektkaczyk/eloquence#6]
Hey guys,

I'm currently trying your amazing package. During documentation reading I came to the point where you extend the model like this:

```
class User extends \Eloquent {

}
```

Are you sure this works? In my opinion there is no class with that name. What you mean is Illuminate\Database\Eloquent\Model, right?

**Comment by bobbybouwmann** [comment]
class User extends \Eloquent is the laravel 4 way, some stuff of the documentation is updated, some stuff isn't

This is updated: https://github.com/jarektkaczyk/eloquence/wiki/Builder-searchable-and-more
This is not: https://github.com/jarektkaczyk/eloquence/wiki/Validable

**Comment by bart** [comment]
Ah okay, perfect. Thanks!
I'm trying to use the Mappable trait but getting the same result as without the mapping :(

**Comment by jarektkaczyk** [comment]
@bart About the `Eloquent` - I personally never use this alias, but it's perfectly fine to extend `\Eloquent` instead of the `Model`, (in L, not sure about Lumen) since it's alias.

About the mappings - let's talk about it in the forum

**Comment by bart** [comment]
Thanks a lot @jarektkaczyk !
