### ISSUE TITLE
Ignoring HTML tags while searching

### ISSUE THREAD

**Issue by prasadrajandran** [jarektkaczyk/eloquence#60]
Hey,

Anyone know if it's possible for the search function to ignore HTML tags while searching through a model?

Here's an example of what I mean:
Let's say I have a table called `contacts` with a column called `contacts.description`. In `description`, HTML tags are saved so we could have something like `'<p>Is a person</p>'` as a description of a `contact`.

Right now, running something like this:

`$q = 'Is a person';`
`Contact::search($q);`

Results in zero matches unless I change query to `$q = '<p>Is a person</p>'`.

Note:
**I'm currently using the 5.1 branch of eloquence.**

**Comment by bobbybouwmann** [comment]
DId you try to run the query as a like query?
```
$q = 'Is a person';
Contact::search('%' . $q . '%');
```

**Comment by prasadrajandran** [comment]
I did try that before posting but I haven't fully tested it out to see how it would affect relevance. 

So far I get the results I want but a few things (in terms of relevance) get moved around.

Also I don't know if it's a bad idea to add the '%' wildcard in between all the blank spaces too? For example:
`$q = 'this is my search query'` --(processing)--> `$q = '%this%is%my%search%query%'`

Doing that might help with content that includes `<strong></strong>` elements inside of `<p></p>` elements but once again, no idea if it would affect relevance negatively.

In the next few days, I'll be testing out the search function and if all goes well, I'll close this. In the meantime, I'll leave it open in case anyone else has better ideas.

**Comment by SirLamer** [comment]
For performance reasons you might care to pre-process another database column of your description column with the HTML content already stripped out, then run your search against that but  present the HTML-formatted equivalent in the same row back to the client. Fulltext search is already exhaustive enough, and performance would be massively harmed if also parsing and stripping out HTML / XML content on all entries every time.

Remember, the traditional SQL built-in indexes cannot make use of a prepared index if your search query has a wildcard anywhere except at the very end of the query string. MySQL 5.6 and on has a special "fulltext" index implementation which you could use, however none of Laravel's built-in features support working with it so you'd have to rely on raw MySQL queries, or build your own interface, or find another interface package for fulltext indexes.
https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html

**Comment by jarektkaczyk** [comment]
@prasadrajandran Searchable feature of this package aims to be easy-to-use search with rank and it doesn't focus on such edge cases like yours. Thus I'd up @SirLamer 's suggestion to preprocess your column and strip tags (column or a db view maybe?) and then use searchable.

Regarding your question about inserting `%` wildcard - you could do that, but I don't think it will help you in any way.

**Comment by prasadrajandran** [comment]
Yeah, thinking about it, @SirLamer's suggestion is probably my best bet.
