### ISSUE TITLE
Search not working on related model

### ISSUE THREAD

**Issue by harishtoshniwal** [jarektkaczyk/eloquence#61]
Hey @jarektkaczyk search is not working on the related models. Code is below :

**1. My model (member.php)**

```
protected $searchableColumns = [
	    'member_code' => 20,
	    'name' => 20,
        'contact' => 20,
	    'Plan.plan_name' => 20,
    ];

    //Relationships

    public function Plan()
    {
    	return $this->belongsTo('App\Plan','plan_id');
    }

```

When I search for any plan name for example i search for '**Gym + Cardio 1 month**' , I get all the records with plan names having the word '**Gym**' in it irrespective of the other **2-3 words after it**.
Any fix or am i doing something wrong? Help!

**Comment by jarektkaczyk** [comment]
@harishtoshniwal what do you expect vs. the actual result?

By default it searches for each single word, if you wanted only complete phrase, then wrap it in double quotes `' "Gym + Cardio 1 month" '`

**Comment by harishtoshniwal** [comment]
@jarektkaczyk Fuzzy search! okay. Just a last doubt then, when i search the inverse example **'Cardio + gym 1 month'** rather than _'Gym + cardio 1 month'_ , i get no results! What's the fix for this?

**Comment by harishtoshniwal** [comment]
@jarektkaczyk oh fuzzy search okay thank you :) But why you be so rude buddy?

**Comment by mikemclin** [comment]
@harishtoshniwal I think you might have misunderstood the reply.  He was simply asking what were you expecting?

Think of the search like Google (but much simpler obviously).  The whole term does not have to match.  There are ranking algorithms in place.  So, in your example, I would expect that anything that has the word `Gym` would match, however the records that have multiple matching words, would have a higher rank, and come first in the results collection.

**Comment by harishtoshniwal** [comment]
@mikemclin yeah i got it, might be misunderstanding at my end, just 19 so might sound off the track when it comes to formal communication :) Cheers!
