### ISSUE TITLE
Feature request: Per-relationship assignment of "fulltext" search method

### ISSUE THREAD

**Issue by SirLamer** [jarektkaczyk/eloquence#62]
There will be lots of cases where the match type will differ based on the data "column" we are looking to match with. Since the fulltext search method is much more computationally expensive than the others, it would be a significant performance enhancement if it were possible to specify which relationship sets are searched via fulltext method and which won't. Effectively, the intent is to be able to make use of table indexes as much as possible without forbidding it on a few columns. Given the nested query method used by this package, it should be doable.

So, considering a "Project" model with various pick list-type relationships, here is a likely scenario:
- "ID" column may require exact match only
- "Project name" column will often require fulltext search because these may be a long descriptive string
- "Project's client name" field may be desired to be run with fulltext search, or maybe not
- "Project type" attribute column can be search using "LIKE 'my_search%' " method which will use the index
- "Project status code", "Responsible employee name", etc. probably don't need fulltext search

This is a fantastic enhancement package, in particular the Mappable feature is enabling very straightforward and efficient UI column sorting even using nested relationships. Awesome stuff!

**Comment by jarektkaczyk** [comment]
Thanks, can you give me short pseudo-code example of such query?

**Comment by SirLamer** [comment]
Sorry for pissing off...

I imagine the user-side implementation would be something like this in the model:

>     protected $searchableColumns = [
        'id' => [
        'weight' => 100
        'type' = 'exact'
        ],
                'name' => [
        'weight' => 90,
        'type' => 'fulltext'
        ]
                'client.name' => [
        'weight' => 40,
        'type' => 'fulltext'
        ]
                'type.name' => [
        'weight' => 10,
        'type' => 'index'
        ]
                'status.name' => [
        'weight' => 10,
        'type' => 'index'
        ]
    ];

I haven't dug through your code but have looked at the produced SQL queries. It looks like your code basically generates the "index" and "fulltext" queries and stitches them together alongside a weighting assignment for a match in each query.

Note I just picked the 'type' names and stuff on the fly here, I don't doubt that with some more thought there could be some clearer schema for the user.

**Comment by jarektkaczyk** [comment]
@SirLamer sorry for late reply. I don't think I could make it happen right now. It adds a lot of complexity while probably being rather an edge case.

If you fancy a PR, then go for it and reference this issue, for now I'm closin it.
