### ISSUE TITLE
Date format not honored when using Mappable column aliases 

### ISSUE THREAD

**Issue by PancakeTornado** [jarektkaczyk/eloquence#64]
Using Laravel 5.2, I'm having trouble getting a couple datetime columns (MySQL), which I have aliased in my model class using Mappable, to honor the Laravel datetime format via the ```protected $dates = [];``` member variable.

In my ```Admin``` Model class, when I view the JSON produced from ```Admin::all()``` I received the datetime columns I have aliased displayed in the format:
```json
"created_at": {
      "date": "2010-11-02 23:59:46",
      "timezone_type": 3,
      "timezone": "UTC"
    },
```
However, it seems like the ```protected $dates = ['created_at'];``` property in my model class should be getting honored to produce the JSON date value in the desired format:
```json
"created_at": "2010-11-02 23:59:46",
```

When I change my Model to not use column aliasing via Mappable ```$maps```, then the original column name of ```admin_created``` correctly gets displayed as:
```json
"admin_created": "2010-11-02 23:59:46",
```

The only workaround that I've found which seems to work is to add what seems like duplicate code by manually creating an attribute mutator:
```php
public function getAdminCreatedAttribute($value)
{
    return $this->serializeDate($this->asDateTime($value));
}
```

This seems like a bug in Mappable that it does not honor the ```$dates``` property for aliased columns, however I'm new to Laravel and may be configuring my model incorrectly. Is this a bug or am I not using Mappable correctly?

```php
namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;

class Admin extends Authenticatable
{
    use Eloquence, Mappable;

    protected $table = 'admin';
    protected $primaryKey = 'admin_id';

    const CREATED_AT = 'admin_created';
    const UPDATED_AT = 'admin_modified';

    protected $dates = ['created_at', 'modified_at'];
    
    protected $maps = [
        // Column alias in code => MySQL column name
        'id' => 'admin_id',
        'role_id' => 'admin_groups_id',
        'firstname' => 'admin_firstname',
        'lastname' => 'admin_lastname',
        'email' => 'admin_email_address',
        'password' => 'admin_password',
        'created_at' => 'admin_created',
        'modified_at' => 'admin_modified',
    ];
    
    protected $appends = [
        'id',
        'role_id',
        'firstname',
        'lastname',
        'email',
        'password',
        'created_at',
        'modified_at',
    ];
    
    protected $visible = [
        'id',
        'role_id',
        'firstname',
        'lastname',
        'created_at',
        'modified_at',
        'admin_created',
    ];
    
    protected $fillable = [
        'role_id',
        'firstname',
        'lastname',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];
}
```

**Comment by jarektkaczyk** [comment]
@PancakeTornado It just works - you must be doing something wrong.

Show me exact code you're running.

**Comment by PancakeTornado** [comment]
The only code I'm running is a very simple ``Route::resource('admins', 'AdminsController');`` route to an index method in a controller which does:
```php
return Admin::all();
```
This produces the JSON results I reported above - displaying the date in a format which does not match what you would expect. The database behind my model is MySQL with a created and updated column names different than the standard `created_at` and `updated_at`.

The only reason I can think of why I have to do my mutator workaround, as mentioned above, is due to the column aliasing declared via Mappable.

I am using PHP  5.5.9 and Laravel 5.2 with the latest Eloquence package to date via `composer update`.
