### ISSUE TITLE
Search meta attributes

### ISSUE THREAD

**Issue by chrisbaswell** [jarektkaczyk/eloquence#65]
Is it possible to search the meta attributes of an entity?  I've looked through your documentation and past issues but can't seem to find an answer.

**Comment by jarektkaczyk** [comment]
If by `search` you mean querying, then yes, you can do that. Check examples in the [wiki](https://github.com/jarektkaczyk/eloquence/wiki/Metable) at the very bottom

**Comment by chrisbaswell** [comment]
I'm sorry. I meant using the search function of Eloquence to find meta values.  

`User::search('meta_value');`

**Comment by jarektkaczyk** [comment]
That's not supported currently.
