### ISSUE TITLE
Mutator overridden by Mappable

### ISSUE THREAD

**Issue by sarahkemp** [jarektkaczyk/eloquence#67]
I have several field names from a legacy database that contain characters not allowed in PHP function names (like '#'). I use Mappable to overcome this obstacle, but I cannot write mutators for these fields because `getIvprt#Attribute()` is not a valid function name. I would like to use the mapped key for the mutator, but when I do, the returned value is overridden by the Mappable hook after the mutator is run.  For example:

    class InventoryItem extends Model{
        use \Sofa\Eloquence\Eloquence;
        use \Sofa\Eloquence\Mappable;

        protected $maps = [
            'id' => 'IVPRT#', 
            ...
            'weight' => 'IV#'; // contains the weight per hundred items

        public function getWeightAttribute($val){
            return $this->attributes['IV#'] / 100; // turns the weight per hundred into weight each
        }
    }

This all works fine until: https://github.com/jarektkaczyk/hookable/blob/5.2/src/Hookable.php#L95 calls the hook on getAttribute in Mappable: 

    public function getAttribute()
    {
        return function ($next, $value, $args) {
            $key = $args->get('key');
            if ($this->hasMapping($key)) {
                $value = $this->mapAttribute($key);
            }
            return $next($value, $args);
        };
    }

Which sees that I have mapped weight to IV# and returns the value of IV# un-mutated. If I had a mutator called `getIv#Attribute()` this would not be a problem, but I cannot. 

In this particular case I will rename 'weight' to 'hundred_weight' and the issue will clear up since there will no longer be a mapping for 'weight', unfortunately I have many illegible and illegal field names so I know this will come up again. 

I realize my legacy database is probably a worst-case and rare situation so this may not be an issue for anyone else, but I thought I would point it out since everything else about Mappable seems to work as expected, except mutators which cannot use the mapped key. 

Thanks for reading.

**Comment by jarektkaczyk** [comment]
Try this:

```
class InventoryItem extends Model{
    use Eloquence, Mappable, Mutable;

    protected $getterMutators = [
        'weight' => 'divide:100' // get weight per item
    ];

    protected $maps = [
        'id' => 'IVPRT#', 
        ...
        'weight' => 'IV#'; // contains the weight per hundred items
}

// define global function somewhere:
/**
 * Divide number.
 *
 * @param  float $dividend
 * @param  float $divisor
 * @returns float
 */
function divide($dividend, $divisor = 1)
{
    return $dividend / $divisor;
}
```

**Comment by jarektkaczyk** [comment]
Does this help @sarahkemp ? If so, please close the issue.

**Comment by sarahkemp** [comment]
In this particular case I won't need the custom function mapping because I renamed my column mapping to avoid the overlap. I wanted to post the issue more for the sake of anyone trying to solve this problem too. Thank you for your suggestion as well, it may be just what I need for some of my other unfortunate column names. 

Thank you for these plugins.
