### ISSUE TITLE
check if mapped attributed is casted to json

### ISSUE THREAD

**Issue by pelim** [jarektkaczyk/eloquence#68]
when working with pgsql json fields dot attributes schuld not be interpreted as relation

``` php
protected $casts = [
    'domains'  => 'json'
];

protected $maps = [
    'domains.primary' => "domains->'primary'"
];

```

**Comment by jarektkaczyk** [comment]
Casting to `json` does not necessarily mean json field in the db, so we can't assume that. 

But I guess we can simply adapt the new `json` querying that is going to be introduced soon:

```
$maps = [
   'primary' => 'domains->primary',
];
```

Can you make a PR for this?
