### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by naumanahmed19** [jarektkaczyk/eloquence#72]
I am newbie to larvel and its packages. I am using only database component ( https://github.com/illuminate/database) for my angular based app with slim framework.

I want to add this package to my app. I have read installation instruction but unable to figure out point 4
```Add Sofa\Eloquence\ServiceProvider to your config/app.php providers array - it will register the Mutator as a service in the IoC Container as well as factories on the Builder class```

right now i am getting this error 
```Fatal error: Call to a member function make() on null in \vendor\sofa\eloquence\src\Builder.php on line 77```

I don't have config/app.php in my application. Is there any alternative? by using singleton or require?

**Comment by dfdgsdfg** [comment]
I try to several classes resist to a slim container, and try to wire it, but it seems not to work.

Any suggest?

```
$container['eloquence.mutator'] = function ($c) {
    return new Mutator;
};
$container['eloquence.joiner'] = $container->factory(function ($c) {
    return new JoinerFactory;
});
$container['eloquence.parser'] = $container->factory(function ($c) {
    return new ParserFactory;
});
```
```
//In my model class
use Eloquence, Mappable;

public static function bootEloquence() {
    static::observe(new AttributeCleaner);
        if (!isset(static::$attributeMutator)) {
            $mutator = app()->getContainer()->get('eloquence.mutator');
            static::setAttributeMutator($mutator);
        }
    }
}
```

**Comment by mirzazeyrek** [comment]
Same issue here. Only using database component with wordpress and stuck at same message.

Fatal error: Call to a member function make() on null in /var/www/vhosts/domain/themes/wp-content/themes/v4/app/APIs/orm/vendor/sofa/eloquence/src/Builder.php on line 87

**Comment by dfdgsdfg** [comment]
Check below.

https://github.com/jarektkaczyk/eloquence/issues/18

```php
use Illuminate\Support\ServiceProvider as Provider;
use Sofa\Eloquence\ServiceProvider as Eloquence;

$container['eloquence'] = function ($c) {
     $eloquence = new Eloquence('Sofa\Eloquence\ServiceProvider');
     return $eloquence;
};

$eloquence = $container()->get('eloquence');
$eloquence->boot();
```

**Comment by spagu** [comment]
`Fatal error: Uncaught Error: Class 'Sofa\Eloquence\ServiceProvider' not found in /services/bootstrap/app.php:69 Stack trace: #0 /services/public/index.php(3): require() #1 {main} thrown in /services/bootstrap/app.php on line 69`

this error I am getting with latest update.

**Comment by odahcam** [comment]
As said in https://github.com/jarektkaczyk/eloquence/wiki/Installation, the correct classname is `Sofa\Eloquence\BaseServiceProvider`. So you got: 

```
use Sofa\Eloquence\BaseServiceProvider as EloquenceProvider;

$capsule = new EloquenceProvider(EloquenceProvider::class);
$capsule->boot();
```

Cheers. 😉
