### ISSUE TITLE
Feature Request: joinRelations table alias

### ISSUE THREAD

**Issue by iampatrick** [jarektkaczyk/eloquence#73]
First, thanks and kudos for Eloquence!

Here is my problem / idea. When joining relations, sometimes I'm joining the same table, multiple times.

For example:
`$listdata = assignment::joinRelations(['company','rep','manager','contact','subject'], 'left')`
Where 'rep' & 'manager' are both relationships to table 'users', and 'contact' & 'subject' are both table 'contacts'.

Would it be possible to use the relationship name as the joined table's alias?

**Comment by jarektkaczyk** [comment]
@iampatrick can you make a PR for this?

**Comment by deevus** [comment]
@jarektkaczyk Do you have any preferences about how this should work? My gut is that the name of the relation should become the name of the join alias, perhaps using `str_plural` so in the original example:

```php
$listdata = assignment::joinRelations(['company','rep','manager','contact','subject'], 'left')
    ->where('companies.id', 1234)
    ->where('reps.id', 4321);
```

Thoughts?

**Comment by deevus** [comment]
Perhaps a way around it being a breaking change is an opt-in function like `prefixColumnsForJoin`
