### ISSUE TITLE
Metable data not shown while value set to 0, false, null

### ISSUE THREAD

**Issue by pushkin42** [jarektkaczyk/eloquence#75]
Except unset($user->metaVariable), same effect takes set it value to 0, false or null.

It will be right, but what happens when I need to store **zero** value into metable variable?

![scr1](https://cloud.githubusercontent.com/assets/8026462/14173986/8c6d21d6-f752-11e5-83e0-d46934acb363.png)
![scr2](https://cloud.githubusercontent.com/assets/8026462/14173987/8c6f8fc0-f752-11e5-9bb6-9c33911f7c2f.png)

**Comment by jarektkaczyk** [comment]
Can you provide a PR for this?

**Comment by pushkin42** [comment]
What is PR, sorry?

**Comment by pushkin42** [comment]
What exactly I need to write in a PR?

**Comment by jarektkaczyk** [comment]
a Pull Request with functionality you'd like to have ;)

**Comment by devfelipereis** [comment]
I have the same issue using Laravel 5.1.

I have a meta_key = status and meta_value = 0. It doesn't show when using toArray but I can access as an attribute.

I my case,  I have a collection of objects that have the meta_key status and I'm using them in a method(from datatables package) that uses them as array in view. If the value is 0, I can't access the status in view. If I set to 555 for example, it shows.

Any help?
