### ISSUE TITLE
Searchable: self-joined relations‏

### ISSUE THREAD

**Issue by theplayer777** [jarektkaczyk/eloquence#76]
Hello,

First I’d like to thank you for your Searchable extension for Laravel. It’s really great and it saved me a lot of time! Despite that, I still have some issue using it for “complex” research: I want to make research through multiple self-joined relations, here is an example:

In my model, companies can have multiple addresses. Addresses are each linked to one location (city). Finally, a location can have multiple parent locations (city->region->country). I want to be able to search companies by their location name (“addresses.location.name”) but also by their parent location name doing something like “addresses.location.parent.name”, but this returns me an error:

SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'location'

I think it’s because the query tries to join location table multiple times without using aliases… Do you think there’s any possibility to do something similar with this model?

Thank you in advance

**Comment by mani1986** [comment]
I second this, self joins or multiple joins to the same table are not working due to an alias conflict. I hope this could be fixed. 

Also, thank you for a great plugin.

**Comment by jarektkaczyk** [comment]
I'm unable to go for it now, so maybe a PR ?
