### ISSUE TITLE
Explicit Mapping with Aliases

### ISSUE THREAD

**Issue by sarahkemp** [jarektkaczyk/eloquence#78]
It just blew my mind a little when I realized what I could do with explicit mapping to order my models by their relationships. Amazing plugin. 

I did encounter one question: is it expected that I cannot use my mapped aliases from the related model in the explicit relationship mapping of the model? E.g. I cannot:

    class Customer extends Model{
        use \Sofa\Eloquence\Eloquence;
        use \Sofa\Eloquence\Mappable;

        protected $maps = ['id' => 'CUCUST',
                           'name' => 'CUNAME',
                           ...];
    }

    class Quote extends Model{
        use \Sofa\Eloquence\Eloquence;
        use \Sofa\Eloquence\Mappable;

        protected $maps = ['customer_name' => 'customer.name']; // if I use customer.CUNAME, this works

        public function customer(){
            return $this->hasOne('...Customer', 'CUCUST', 'customer_id');
        }
    }

When the Quote class maps `customer_name` to `customer.name` I get: `SQLSTATE[42S22]: Column not found: Column "name" not in table`, but if I use `customer.CUNAME`, it works.

I can work with this if it's the expected behavior, but last time something like this happened and I asked, it was not expected and was fixable. I don't have any illegal mapping this time.

Sidenote, I also can't seem to use the alias in my relationship definitions (see function `customer()`) - it only seems to work when I use the original column name. Is that expected too?

Thanks for reading, and again for the great plugin.

**Comment by zawilliams** [comment]
Encountered this same issue. I can only get the desired column using the original column name when calling the alias through a related model (e.g. 'customer->name' vs 'customer->CUNAME').

Is calling an alias through the related model not possible?

**Comment by jarektkaczyk** [comment]
@sarahkemp @zawilliams Sorry, I must have closed this one by mistake.

Anyway, it is indeed impossible at the moment, since the query mapping happens without checking further mappings on the related models. You can try to play with it and make a PR or let me know and I will do it when I have time. Emphasizing WHEN ;)
