### ISSUE TITLE
Chaining search on separate fields

### ISSUE THREAD

**Issue by nickyadvokaat** [jarektkaczyk/eloquence#79]
Hi,

I'm trying to combine searches on separate columns of my table. This works perfectly:
```javascript
User::search('jare', 'first_name')->get();
```
This also works fine:
```javascript
User::search('tkac', 'last_name')->get();
```

Now what I want to do is find record that match both these criteria:
```javascript
User::search('jare', 'first_name')->search('tkac', 'last_name')->get();
```

However this always results in an empty array [].

I know I can do:
```javascript
User::search(['jare','tkac'], [
    'first_name' => 10,
    'last_name' => 10,
]);
```

But this is not what I want, I don't want to search for the first name in the `last_name` column and vice versa.

Thanks!

**Comment by jbrooksuk** [comment]
It's a shame this isn't possible as this is exactly what I need too! :)

**Comment by pashamesh** [comment]
+1 for that feature

**Comment by jarektkaczyk** [comment]
I don't think it would make sense in terms of performance. If anyone interested please provide a PR that I can play with.

**Comment by jbrooksuk** [comment]
@jarektkaczyk what about passing an array of search arrays?

**Comment by jarektkaczyk** [comment]
The problem is in the logic /query, not how to pass params in the code. We
have pretty big subquery built under the hood and we would need another one
for each additional field - off the top of my head.

Jarek Tkaczyk

softonsofa :: development with pleasure
