### ISSUE TITLE
Saving Mappable models with identical key/value pairs in $maps

### ISSUE THREAD

**Issue by jonpitch** [jarektkaczyk/eloquence#8]
When saving a model that uses the `Mappable` trait, are we unable to have aliases with matching column names? For example:

```php
class MyModel extends \Eloquent {
    use Eloquence, Mappable;

    protected $fillable = ['first_name'];
    protected $maps = [
       'first_name' => 'first_name',
       // ...
    ];
}

// ...

$model = new MyModel;
$model->first_name = 'Jon';
$model->save();
```

The save is successful but the value of `first_name` is not persisted to the database. I can work around the issue by having an alias of a different name. Using version `0.4.13` and Postgres.

**Comment by jarektkaczyk** [comment]
Yes, it is impossible because it makes no sense. Why would you want to have an alias matching aliased column?

**Comment by jonpitch** [comment]
You're right, now that I re-think it through, if the alias is the same as the column, it doesn't need to be mapped.
