### ISSUE TITLE
Search on relationship multiple word field just matches first word

### ISSUE THREAD

**Issue by wolfius** [jarektkaczyk/eloquence#80]
Hi!

I'm using search with the simplest config, just `Model::search($terms)` where `$terms` can be 1 or many words.

I'm noticing that, when I make a search directly on a Model that has a multiple word field, the search matches the terms on any of the words of the field, but if I search on this same field through a relationship from another model, the terms only match the first word.

Example: 

I have a Dealership with name 'Ford Whatever'. If I search `Dealership::search('whatever')` it brings me that dealership, if I search 'ford' it brings me all dealerships that start with that word.

Now I have Salesmans that belongs to Dealership 'Ford Whatever'. If I search (having defined 'dealership.name' as a searchable field) `Salesman::search('Whatever')` it brings me no results, but I know the search is being done in that field because if I search 'Ford', it brings me all salesmen that belong to dealerships that start with 'Ford' (which it really doesn't help much).

I don't think this is working as intended but I'll appreciate if someone could tell me if I'm doing soemthing wrong, or maybe a tip on a workaround?

Thanks!

**Comment by jarektkaczyk** [comment]
It's about the threshold - play with it. Like here https://github.com/jarektkaczyk/eloquence/issues/53

**Comment by wolfius** [comment]
@jarektkaczyk oh wow, thank you! Guess I should've checked how that parameter worked.
