### ISSUE TITLE
Exact search not working with cyrillic values

### ISSUE THREAD

**Issue by wielski** [jarektkaczyk/eloquence#82]
![2016-04-12 11 53 44](https://cloud.githubusercontent.com/assets/6212124/14453338/435f2d02-00a5-11e6-8ab3-084c3aec59aa.png)
Here is the code.

When i search by keyword "Теплый пол Gulfstream КГС1-2120-106" it generates this sql:
![2016-04-12 11 55 04](https://cloud.githubusercontent.com/assets/6212124/14453363/69823dbc-00a5-11e6-9f3e-1c03c5a1162c.png)
So, as you see, it searching by "пол Gulfstream" keyword, first and last words are cut.

**Comment by jarektkaczyk** [comment]
Can you make a PR for this one?
