### ISSUE TITLE
Mappable attributes bad call

### ISSUE THREAD

**Issue by samijnih** [jarektkaczyk/eloquence#83]
Hello,

I have two models, `Song` and `Release`.

Both of them use the Mappable trait.

`Release` defines a protected $maps attribute containing `releasedOn'    => 'released_on',`
When I get a release with its songs (HasMany relationship, eager loading) and I call `$release->releasedOn`, it doesn't work.
When I define the `releasedOn` mapping in the $maps attribute of the `Song` model, and remove the `releasedOn` of the `Release` model, it works doing `$release->releasedOn`

If anybody has a suggestion ?

**Comment by jarektkaczyk** [comment]
Is it still a problem? If so, please paste the models and code you executed along with the expected vs. actual result.

**Comment by samijnih** [comment]
I used an another package development to have pretty attribute on my model so I don't have the code sorry :/

maybe I just did some shit
