### ISSUE TITLE
Having trouble on Mapable

### ISSUE THREAD

**Issue by abhikchakraborty** [jarektkaczyk/eloquence#87]
Hello team,
I am new to Lumen framework and mostly worked with NODE.JS to built RESTFul API with Waterline ORM where I could map the column name as I want in the model https://github.com/balderdashy/waterline-docs/blob/master/models/data-types-attributes.md#columnname something as 
```
dateAdded: {
			type: 'date',
			columnName: 'date_created'
		}
```
I am now implementing a RESTFul API with PHP and found Lumen is the best. I have a legacy DB where the column names are not in camel case and I want the response should be in camel case in JSON. 

So I found this package and installed it as per the doc https://github.com/jarektkaczyk/eloquence/wiki

Now I have a very simple end point to return all the contacts and this is what I did so far

Added the service as 
```
$app->register('Sofa\Eloquence\ServiceProvider');
```
in `bootstrap/app.php`

I could see the package inside the `vendor folder`

Now in the model file under `app` folder is as
```
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence; // base trait
use Sofa\Eloquence\Mappable; // extension trait

class Contacts extends Model {
	use Eloquence, Mappable;
	protected $table = 'contacts';
	protected $visible = ['firstname', 'lastname'];
	protected $maps = [
		'firstname'=> 'firstName',
		'lastname' => 'lastName'
	];
}
```

So when I hit the end point which is `mydomain/api/v1/contacts` I see the JSON being returned as expected but not in camel case.

My controller is pretty simple 
```
<?php

namespace App\Http\Controllers;
use App\Contacts;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactsController extends Controller
{
	public function getAll() {
		$contacts = Contacts::all();
		return response()->json($contacts);
	}
}
```
I did some debug by using `$contacts = Contacts::all()->toArray();` and `print_r` does not show the column name in camel case.

### Under the hood 

- The version of laravel I have as
```
php artisan --version
Laravel Framework version Lumen (5.2.6) (Laravel Components 5.2.*)
```
- As per the doc https://github.com/jarektkaczyk/eloquence/wiki/Installation I do not have a `config/app.php` hence I added the service as 
```
$app->register('Sofa\Eloquence\ServiceProvider');
```
in `bootstrap/app.php` as mentioned before.

- I get the response as 
```
[
 {
    "firstname":"Abhik",
    "lastname":"Chakraborty"
 },
 {
    "firstname":"John",
    "lastname":"Martin"
 }
]
```
My expected result would be `firstname` as `firstName` and `lastname` as `lastName`
Please let me know if I am missing something obvious.

**Comment by jarektkaczyk** [comment]
Hey, by using `$visible` property you explicitly told eloquent to show only `firstname` and `lastname`. Try replacing them with camelCased keys and you should be fine.
When you don't use `hidden/visible` at all you should get both version in your json representation of the model.
Close the issue if that resolves the problem.

**Comment by abhikchakraborty** [comment]
Hi there ! As you mentioned I have made by `$visible` property commented and the model now looks like
```
namespace App;
use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence; // base trait
use Sofa\Eloquence\Mappable; // extension trait

class Contacts extends Model {
	use Eloquence, Mappable;
	protected $table = 'contacts';
	protected $primaryKey = 'idcontacts';
	//protected $visible = ['firstName', 'lastName','idorganization'];
	protected $maps = [
		'firstName'=> 'firstname',
		'lastName' => 'lastname'
	];
	
	public function organization() {
        return $this->hasOne('App\Organization','idorganization');
    }
}
```
still no luck.

### Additional information
As described in the doc https://github.com/jarektkaczyk/eloquence/wiki/Mappable the example is extending the class as
```
class User extends \Eloquent {

```
However in my case its 
```
class Contacts extends Model {
```

**Comment by abhikchakraborty** [comment]
Hey, I was doing some debug last 2 days and kind of reach the dead end and can't find anything after words 

The 2 models I have as

```php
namespace App;
use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence; // base trait
use Sofa\Eloquence\Mappable; // extension trait

class Contacts extends Model {
	use Eloquence, Mappable;
	protected $table = 'contacts';
	protected $primaryKey = 'idcontacts';
	protected $visible = ['firstName', 'lastName','organization'];
	protected $maps = [
		'firstName' => 'firstname',
		'lastName' => 'lastname'  
	];
	
	public function organization() {
        return $this->belongsTo('App\Organization','idorganization');
    }

namespace App;
use Illuminate\Database\Eloquent\Model;

class Organization extends Model {
	
	protected $table = 'organization';
	protected $primaryKey = 'idorganization';
	protected $visible = ['organization_name', 'website','website','phone','num_employes','industry'];
	
}
```

The controller is pretty simple 
```php
namespace App\Http\Controllers;
use App\Contacts;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactsController extends Controller
{
	public function getAll() {
		$contacts = Contacts::with('organization')->get();
		return response()->json($contacts);
	}
}

```

Now it does not return the `firstName` and `lastName` into the response json. 
I tried to remove the relation and just used `$contacts = Contacts::all();` instead however this also does not have any effect and `firstName` and `lastName` still missing from the JSON, if I do not choose any `$visible`  property or use the column names as in the DB it works with or without the relation.

I further went inside the core of the library and under `vendor/Sofa/eloquence/src/Mappable.php` tried to print `$mappedAttributes[$attribute]` in `protected function parseMappings()` and I could see the map values as defined in the `$maps`

Also if I print `$contacts` in controller  `ContactsController` I could only see the DB columns not the mapped one.

The array looks like 
```php
[table:protected] => contacts
                    [primaryKey:protected] => idcontacts
                    [visible:protected] => Array
                        (
                            [0] => firstname
                            [1] => lastName
                            [2] => organization
                        )

                    [maps:protected] => Array
                        (
                            [firstName] => firstname
                            [lastName] => lastname
                        )

                    [connection:protected] => 
                    [perPage:protected] => 15
                    [incrementing] => 1
                    [timestamps] => 1
                    [attributes:protected] => Array
                        (
                            [idcontacts] => 1
                            [firstname] => Abhik
                            [lastname] => Chakraborty
                            .................................
                            .................................
                        )

                    [original:protected] => Array
                        (
                            [idcontacts] => 1
                            [firstname] => Abhik
                            [lastname] => Chakraborty
                            ...................................
                            ...................................
                        )
```

Hope this might help you to detect what I am doing wrong.

**Comment by gabimem** [comment]
Hi, I had this problem and solved it by setting in '$hidden' the old fields and in '$appends' the new fields.
e.g.

```php
namespace App;
use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence; // base trait
use Sofa\Eloquence\Mappable; // extension trait

class Contacts extends Model {
    use Eloquence, Mappable;
    //...
    protected $maps = [
        'firstName' => 'firstname',
        'lastName'  => 'lastname'
    ];
    protected $hidden  = ['firstname', 'lastname'];
    protected $appends = ['firstName', 'lastName'];
    //...
```
I think this solves this issue.
GM
