### ISSUE TITLE
Eloquence Model doesn't work well with Validable?

### ISSUE THREAD

**Issue by ziming** [jarektkaczyk/eloquence#9]
When my model code is this, seeding doesn't work

```
<?php namespace App;

use Sofa\Eloquence\Model;
use Sofa\Eloquence\Mutable;

class LetterType extends Model {

    use Mutable;

    protected $fillable = ['title', 'acronym', 'description'];

    /**
     * Attributes getter mutators @ Eloquence\Mutable
     *
     * @var array
     */
    protected $getterMutators = [

    ];

    /**
     * Attributes setter mutators @ Eloquence\Mutable
     *
     * @var array
     */
    protected $setterMutators = [
        'acronym' => 'trim',
    ];

    protected static $rules = [
        'title'  => 'required',
        'acronym' => 'required',
    ];
}
```

Seeding only works when I change to:

```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Contracts\CleansAttributes;
use Sofa\Eloquence\Contracts\Validable as ValidableContract;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;
use Sofa\Eloquence\Mutable;
use Sofa\Eloquence\Validable;

class LetterType extends Model implements ValidableContract, CleansAttributes {

    use Eloquence, Mutable, Validable;

    protected $fillable = ['title', 'acronym', 'description'];

    /**
     * Attributes getter mutators @ Eloquence\Mutable
     *
     * @var array
     */
    protected $getterMutators = [

    ];

    /**
     * Attributes setter mutators @ Eloquence\Mutable
     *
     * @var array
     */
    protected $setterMutators = [
        'acronym' => 'trim|strtoupper',
    ];

    /**
     * Rules for field attributes
     * Available rules as described in the laravel docs:
     * @link http://laravel.com/docs/5.0/validation#available-validation-rules
     */
    public static $rules = [
        'title'  => 'required',
        'acronym' => 'required',

    ];

}
```

This is strange to me because for my User model, extending Sofa\Eloquence\Model gives me no issue in seeding. But for my LetterType model, it does.

**Comment by bobbybouwmann** [comment]
What error do you get? Any other relevant information?

**Comment by ziming** [comment]
@bobbybouwmann it will say Seeded:... in console but in reality nothing got seed for that table. laravel.log has nothing too.

**Comment by bobbybouwmann** [comment]
You don't exstend the `LetterType` class with Eloquence, I think the issue is there
```
// This

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mutable;

class LetterType extends Model {

// Should be
use Sofa\Eloquence\Model;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mutable;

class LetterType extends Model {
```

**Comment by ziming** [comment]
Hi @bobbybouwmann in my example, seeding fails when I extends Sofa\Eloquence\Model. but it works when I extends use Illuminate\Database\Eloquent\Model and use the validable traits and interface instead.

**Comment by ziming** [comment]
Hi further investigation shows to me that it is Validable that's causing the problem.

I tested this by creating an AppModel abstract class and extends it from my other models.

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Contracts\CleansAttributes;
use Sofa\Eloquence\Contracts\Validable as ValidableContract;
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;
use Sofa\Eloquence\Mutable;
use Sofa\Eloquence\Validable;

abstract class AppModel extends Model implements ValidableContract, CleansAttributes
{
    use Eloquence, Mutable, Mappable, Validable;

}
```

When I remove ValidableContract, CleansAttributes and Validable, from the super class then it works.

I don't think it is an issue with my validation rules if any because when my concrete classes implements ValidableContract, CleansAttributes and use the Validable trait, seeding works fine. It just fails if these are in my superclass instead.

**Comment by jarektkaczyk** [comment]
@ziming @bobbybouwmann I'm on holiday, I will take a look at this in a few days. If you can do it sooner, then pls do. Thanks

**Comment by bobbybouwmann** [comment]
@jarektkaczyk I don't have much time this week, so I can't take a look at it for now. I bet you will be back sooner then I am ;)

**Comment by ziming** [comment]
Update, I notice more problems this time when I use middleware. Got to implement the contracts and traits in the class itself instead of extending the super class for it to work again. Hope it helps!.

**Comment by jarektkaczyk** [comment]
@ziming I've tested that on L5.0 and nothing bad happens. Seeding works as expected, so if the problem persists, please upload whole code so I can see it.

**Comment by ziming** [comment]
I am using laravel 5.1 and mostbof the time the issue happen when using it with laravel administrator. I'm outside now so I can't test it right now. Sometimes the problem is solved by running php artisan optimize. Sometimes isn't. Thank you.
