### ISSUE TITLE
Searching with array data

### ISSUE THREAD

**Issue by cbiong** [jarektkaczyk/eloquence#91]
i have this column called colors inside users table with example data pink,white,red,violet

all of my column inside users table like (name, section, age) are searchable except for the data inside colors column

here is what i have inside my controller

``
User::search($request->input('search-key'),
    		$fulltext = false)->get();
``

example data from db
name: john doe
age: 7
section: c1
colors: pink,white,red,violet

**Comment by jarektkaczyk** [comment]
I think we're missing the question here ;)

Anyway, I guess you'd like to search the comma-separated values - it's just string, so will work with fulltext option.
