### ISSUE TITLE
Search key bug

### ISSUE THREAD

**Issue by cbiong** [jarektkaczyk/eloquence#92]
There's a bug with the search key when combined with the other database column

here is a sample data from my database "apple,orange,banana"
when you use any of apple,orange or banana it will return nothing

i have table column of "person, fruits, price"
when i search apple it will return nothing but when i typed the existing name of person it will return the data

**Comment by jarektkaczyk** [comment]
If you don't use fulltext option, then it won't find anything in CSV string.
