### ISSUE TITLE
Mappable: mapped attributes doesn't work in new Model instance

### ISSUE THREAD

**Issue by vmartins** [jarektkaczyk/eloquence#93]
```php
<?php namespace App;

use Sofa\Eloquence\Eloquence; // base trait
use Sofa\Eloquence\Mappable; // extension trait

class User extends \Eloquent {

    use Eloquence, Mappable;

    protected $maps = [
      'profile' => ['first_name', 'last_name'],
    ];

    public function profile()
    {
      return $this->hasOne(Profile::class);
    }
```
Mapped attributes are always `null` when creating new instance model:
```php
$user = new User();
$user->first_name = 'John Doe';
var_dump($user->first_name); //print: null
```

But if I create a new instance of relationship, it works!
```php
$user = new User();
$user->profile = new Profile();
$user->first_name = 'John Doe';
var_dump($user->first_name); //print: John Doe
```

This is expected?

**Comment by jarektkaczyk** [comment]
Yes, this is expected. Since you want to get the value from related model, and there's no related model, ten it will be null.
Mappable doesn't go ahead to create a new instance of that relation for you, since it could lead to unexpected behaviour when that relation is being saved.
