### ISSUE TITLE
'getCreateRules()' becomes attached to the first model it is called on for each session

### ISSUE THREAD

**Issue by SirLamer** [jarektkaczyk/eloquence#95]
I have a scenario where I am populating two separate models using one form, so I want to combine the validation rules. Through this, I found that if you call "getCreateRules()" on two different models, the output will basically become bound to whatever is produced for the first model when calling this on subsequent models. The expected behavior would be separate and different validation rule sets.

Example rules from "Office" model:

``` php
protected static $rules = [
    'name' => 'bail|required|string|min:4|max:32|unique:offices',
    'code' => 'bail|required|string|alpha|size:3|unique:offices',
];
```

Example rules from "Address" model:

``` php
protected static $rules = [
    'city_id' => 'bail|required|integer|exists:cities,id',
    'street' => 'string|required_with:street_extra',
    'street_extra' => 'string',
    'postal_code' => 'string',
    'latitude' => 'numeric|max:90|min:-90',
    'longitude' => 'numeric|max:180|min:-180',
    'place_id' => 'alpha_num',
];
```

Runtime example 1:

``` php
$one = Office::getCreateRules();
$two = Address::getCreateRules();
dd(array_merge($one, $two));
```

Output 1:

> array:2 [▼
>   "name" => array:6 [▶]
>   "code" => array:6 [▶]
> ]

Runtime example 2:

``` php
$one = Office::getCreateRules();
$two = Address::getCreateRules();
dd($two);
```

Output 2:

> array:2 [▼
>   "name" => array:6 [▶]
>   "code" => array:6 [▶]
> ]

Runtime example 3:

``` php
//$one = Office::getCreateRules();
$two = Address::getCreateRules();
dd($two);
```

Output 3:

> array:7 [▼
>   "city_id" => array:4 [▶]
>   "street" => array:2 [▶]
>   "street_extra" => array:1 [▶]
>   "postal_code" => array:1 [▶]
>   "latitude" => array:3 [▶]
>   "longitude" => array:3 [▶]
>   "place_id" => array:1 [▶]
> ]

Runtime example 4:

``` php
$one = [
    'fake_name' => ['stuff', 'things', 'fake'],
    'fake_code' => ['dumb', 'silly', 'useless']
];
$two = Address::getCreateRules();
dd(array_merge($one, $two));
```

Output 4:

> array:9 [▼
>   "fake_name" => array:3 [▶]
>   "fake_code" => array:3 [▶]
>   "city_id" => array:4 [▶]
>   "street" => array:2 [▶]
>   "street_extra" => array:1 [▶]
>   "postal_code" => array:1 [▶]
>   "latitude" => array:3 [▶]
>   "longitude" => array:3 [▶]
>   "place_id" => array:1 [▶]
> ]

**Comment by SirLamer** [comment]
As a fun addition to this...

In the example above, "Office" and "Address" both extend the Eloquence model directly.

Let's add to the mix a new example model "Client". This model implements the contracts and traits instead of extending the model itself. This is done because Client is already an extension of another common-use model I wrote.

Example rules on Client:
```php
    protected static $rules = [
        'name' => 'bail|required|string|min:6|max:250|unique:clients',
        'name_short' => 'string|min:3|max:32|unique:clients',
    ];
```

Runtime example 5:
```php
        $one = Client::getCreateRules();
        $two = Address::getCreateRules();
        dd(array_merge($one, $two));
```

Output 5:
> array:9 [▼
  "name" => array:6 [▶]
  "name_short" => array:4 [▶]
  "city_id" => array:4 [▶]
  "street" => array:2 [▶]
  "street_extra" => array:1 [▶]
  "postal_code" => array:1 [▶]
  "latitude" => array:3 [▶]
  "longitude" => array:3 [▶]
  "place_id" => array:1 [▶]
]

If I go back to either "Office" or "Address" and implement the contracts and traits instead of extending Eloquence per the documentation, then the getCreateRules() method produces the expected output. For the moment, this shall be my work-around.

**Comment by jarektkaczyk** [comment]
Yes, this will be addressed, static context is wrong in this case.

**Comment by CSharpRU** [comment]
Same is for $columnListing and methods that are working with it.

**Comment by GarethTIGFreight** [comment]
Has this issue been resolved or does anyone have a work around?
