### ISSUE TITLE
Model validation on save and update applied without use of get/set attribute methods

### ISSUE THREAD

**Issue by SirLamer** [jarektkaczyk/eloquence#97]
Oftentimes data is stored in a way that is inconsistent with how it is used in practice in the application. In particular, data which is encrypted for storage and decrypted for runtime, such as a remote JSON API key being stored in encrypted form as a security measure. Eloquence Validable performs its check on the raw attribute values (or so it seems) before saving to the database, which may betray the real practical formatting requirements, thus not permitting the use of Eloquence Validable in a way that is useful both for form validation and model attribute validation on save.

So, I'd just suggest that validation should be checked in a way that invokes the "getPropertyAttribute" method when it exists.

**Comment by jarektkaczyk** [comment]
Can you provide a code sample?

**Comment by SirLamer** [comment]
Sorry for the slow response. I don't have a code sample, but as a context, some security-sensitive data which should be encrypted for storage and then decrypted upon retrieval, using the key stored in the environment variables file. In my case these are:
- Two-step verification secret key generated upon the setup handshake
- I am storing API keys for a third-party app, and want to store them as encrypted

Encryption is intended to protect users in case of data theft - a thief would require both the database and the decryption key which will be stored in a file with very strict read/write permission restrictions.

So, obviously validation needs to be performed on the decrypted data, and if get/set attribute methods are created for such properties they can be used by your validator to act on the correct data when checking. Otherwise, I cannot use your validator on such models.
