### ISSUE TITLE
Problem searching in two related models

### ISSUE THREAD

**Issue by ncarreno** [jarektkaczyk/eloquence#98]
I have a products in my ecommerce and each product has its own translation in each language I am using. So I have a Product model where I store the general product data and a ProducLang Model where I store the translations of each language.

I have a single search form in my website to find products. I want to look for information in reference colum that is in my products table (Product model) and in name and description that are in my products_lang table (ProductLang model).

This code doesn't work:
`$result=Product::search(['*' . $request->input('search') . '*'], ['reference','lang.name','lang.description'])->get();`

However this code woks:
`$result=Product::search(['*' . $request->input('search') . '*'], ['lang.name','lang.description'])->get();`

And this one also works:
`$result=Product::search(['*' . $request->input('search') . '*'], ['reference'])->get();`

My Product model code is:

```
//Product Model
...
use Sofa\Eloquence\Eloquence;

class Product extends Model
{
    use Eloquence;
    //I have tried putting only reference, putting nothing and putting reference, lang.name, lang.description into the $searchableColumns but none of these work
    protected $searchableColumns = ['reference'];
...
    public function lang()
    {
        return $this->hasMany('App\ProductLang');
    }
```
What am I doing wrong? Thanks for your help

**Comment by ncarreno** [comment]
I have tried my code in my production server and it works but it takes the web about one minute to show results. Is there any problem using one to many relationship?

**Comment by jarektkaczyk** [comment]
Searchable is very basic implementation that does full table scan, so on medium-size tables joined together it may get slow.
If that's the case I simply suggest going for something more robust, like algolia, solr etc
